// GENERATED by tools/build.js from src/client/ - edit those files, then run `npm run build`.
(function () {
const FPV = {};

// ===== math.js =====
// ---------------------------------------------------------------------------
// math.js - vector / quaternion helpers.
//
// Everything here works on plain {x, y, z} / {x, y, z, w} objects so it can be
// unit-tested in Node without the JC3MP runtime. Conversion to the game's
// Vector3f happens only at the edges (client.js / remote.js).
//
// Frames (right-handed, Y up - matches JC3 world space):
//   world: +X east, +Y up, +Z south
//   body : +X right, +Y up, -Z forward (nose)
// ---------------------------------------------------------------------------

FPV.v3 = function (x, y, z) { return { x: x || 0, y: y || 0, z: z || 0 }; };
FPV.add = function (a, b) { return { x: a.x + b.x, y: a.y + b.y, z: a.z + b.z }; };
FPV.sub = function (a, b) { return { x: a.x - b.x, y: a.y - b.y, z: a.z - b.z }; };
FPV.scale = function (a, s) { return { x: a.x * s, y: a.y * s, z: a.z * s }; };
FPV.dot = function (a, b) { return a.x * b.x + a.y * b.y + a.z * b.z; };
FPV.cross = function (a, b) {
    return { x: a.y * b.z - a.z * b.y, y: a.z * b.x - a.x * b.z, z: a.x * b.y - a.y * b.x };
};
FPV.len = function (a) { return Math.sqrt(a.x * a.x + a.y * a.y + a.z * a.z); };
FPV.dist = function (a, b) { return FPV.len(FPV.sub(a, b)); };
FPV.norm = function (a) {
    const l = FPV.len(a);
    return l > 1e-9 ? FPV.scale(a, 1 / l) : { x: 0, y: 0, z: 0 };
};
FPV.lerp3 = function (a, b, t) {
    return { x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t, z: a.z + (b.z - a.z) * t };
};
FPV.clamp = function (v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); };
FPV.isFiniteVec = function (a) {
    return a && isFinite(a.x) && isFinite(a.y) && isFinite(a.z);
};

FPV.DEG = Math.PI / 180;

// ---- quaternions (Hamilton, q = w + xi + yj + zk) --------------------------

FPV.qIdentity = function () { return { x: 0, y: 0, z: 0, w: 1 }; };

FPV.qMul = function (a, b) {
    return {
        w: a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z,
        x: a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y,
        y: a.w * b.y - a.x * b.z + a.y * b.w + a.z * b.x,
        z: a.w * b.z + a.x * b.y - a.y * b.x + a.z * b.w
    };
};

FPV.qConj = function (q) { return { x: -q.x, y: -q.y, z: -q.z, w: q.w }; };

FPV.qNorm = function (q) {
    const l = Math.sqrt(q.x * q.x + q.y * q.y + q.z * q.z + q.w * q.w);
    if (l < 1e-12) { return FPV.qIdentity(); }
    return { x: q.x / l, y: q.y / l, z: q.z / l, w: q.w / l };
};

FPV.qAxisAngle = function (axis, angle) {
    const n = FPV.norm(axis);
    const s = Math.sin(angle / 2);
    return { x: n.x * s, y: n.y * s, z: n.z * s, w: Math.cos(angle / 2) };
};

// Rotate vector v by unit quaternion q (body -> world when q is the attitude).
FPV.qRotate = function (q, v) {
    // t = 2 * cross(q.xyz, v); v' = v + w * t + cross(q.xyz, t)
    const tx = 2 * (q.y * v.z - q.z * v.y);
    const ty = 2 * (q.z * v.x - q.x * v.z);
    const tz = 2 * (q.x * v.y - q.y * v.x);
    return {
        x: v.x + q.w * tx + (q.y * tz - q.z * ty),
        y: v.y + q.w * ty + (q.z * tx - q.x * tz),
        z: v.z + q.w * tz + (q.x * ty - q.y * tx)
    };
};

// Integrate body-frame angular velocity w (rad/s) over dt.
FPV.qIntegrateBody = function (q, w, dt) {
    const ang = FPV.len(w) * dt;
    if (ang < 1e-12) { return q; }
    const dq = FPV.qAxisAngle(w, ang);
    return FPV.qNorm(FPV.qMul(q, dq));
};

FPV.qSlerp = function (a, b, t) {
    let bx = b.x, by = b.y, bz = b.z, bw = b.w;
    let cos = a.x * bx + a.y * by + a.z * bz + a.w * bw;
    if (cos < 0) { cos = -cos; bx = -bx; by = -by; bz = -bz; bw = -bw; }
    if (cos > 0.9995) {
        return FPV.qNorm({
            x: a.x + (bx - a.x) * t, y: a.y + (by - a.y) * t,
            z: a.z + (bz - a.z) * t, w: a.w + (bw - a.w) * t
        });
    }
    const theta = Math.acos(cos);
    const s = Math.sin(theta);
    const wa = Math.sin((1 - t) * theta) / s;
    const wb = Math.sin(t * theta) / s;
    return { x: a.x * wa + bx * wb, y: a.y * wa + by * wb, z: a.z * wa + bz * wb, w: a.w * wa + bw * wb };
};

// Returns {axis, angle} for use with the game's Matrix.Rotate(angle, axis).
FPV.qToAxisAngle = function (q) {
    q = FPV.qNorm(q);
    if (q.w < 0) { q = { x: -q.x, y: -q.y, z: -q.z, w: -q.w }; }
    const angle = 2 * Math.acos(FPV.clamp(q.w, -1, 1));
    const s = Math.sqrt(1 - q.w * q.w);
    if (s < 1e-6) { return { axis: { x: 0, y: 1, z: 0 }, angle: 0 }; }
    return { axis: { x: q.x / s, y: q.y / s, z: q.z / s }, angle: angle };
};

// Row-major 3x3 rotation matrix (m[row][col]); columns are the body axes in world.
FPV.qToMat = function (q) {
    const x = q.x, y = q.y, z = q.z, w = q.w;
    return [
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)]
    ];
};

// ---- Euler angles ----------------------------------------------------------
// `order` names the intrinsic rotation sequence, e.g. 'YXZ' means
// R = Ry(e.y) * Rx(e.x) * Rz(e.z)  (yaw, then pitch, then roll).
// Formulas follow three.js Euler.setFromRotationMatrix.

FPV.eulerFromQuat = function (q, order) {
    const m = FPV.qToMat(q);
    const m11 = m[0][0], m12 = m[0][1], m13 = m[0][2];
    const m21 = m[1][0], m22 = m[1][1], m23 = m[1][2];
    const m31 = m[2][0], m32 = m[2][1], m33 = m[2][2];
    const c = FPV.clamp;
    const e = { x: 0, y: 0, z: 0 };
    switch (order) {
        case 'XYZ':
            e.y = Math.asin(c(m13, -1, 1));
            if (Math.abs(m13) < 0.9999999) { e.x = Math.atan2(-m23, m33); e.z = Math.atan2(-m12, m11); }
            else { e.x = Math.atan2(m32, m22); e.z = 0; }
            break;
        case 'YXZ':
            e.x = Math.asin(-c(m23, -1, 1));
            if (Math.abs(m23) < 0.9999999) { e.y = Math.atan2(m13, m33); e.z = Math.atan2(m21, m22); }
            else { e.y = Math.atan2(-m31, m11); e.z = 0; }
            break;
        case 'ZXY':
            e.x = Math.asin(c(m32, -1, 1));
            if (Math.abs(m32) < 0.9999999) { e.y = Math.atan2(-m31, m33); e.z = Math.atan2(-m12, m22); }
            else { e.y = 0; e.z = Math.atan2(m21, m11); }
            break;
        case 'ZYX':
            e.y = Math.asin(-c(m31, -1, 1));
            if (Math.abs(m31) < 0.9999999) { e.x = Math.atan2(m32, m33); e.z = Math.atan2(m21, m11); }
            else { e.x = 0; e.z = Math.atan2(-m12, m22); }
            break;
        case 'YZX':
            e.z = Math.asin(c(m21, -1, 1));
            if (Math.abs(m21) < 0.9999999) { e.x = Math.atan2(-m23, m22); e.y = Math.atan2(-m31, m11); }
            else { e.x = 0; e.y = Math.atan2(m13, m33); }
            break;
        case 'XZY':
            e.z = Math.asin(-c(m12, -1, 1));
            if (Math.abs(m12) < 0.9999999) { e.x = Math.atan2(m32, m22); e.y = Math.atan2(m13, m11); }
            else { e.x = Math.atan2(-m23, m33); e.y = 0; }
            break;
        default:
            throw new Error('Unknown euler order ' + order);
    }
    return e;
};

FPV.quatFromEuler = function (e, order) {
    const X = FPV.qAxisAngle({ x: 1, y: 0, z: 0 }, e.x);
    const Y = FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, e.y);
    const Z = FPV.qAxisAngle({ x: 0, y: 0, z: 1 }, e.z);
    const map = { X: X, Y: Y, Z: Z };
    return FPV.qNorm(FPV.qMul(FPV.qMul(map[order[0]], map[order[1]]), map[order[2]]));
};

// ---- JC3 camera conversion -------------------------------------------------
// JC3MP exposes camera.rotation as a Vector3f of euler angles (x = pitch,
// y = yaw, z = roll). Existing freecam packages show that positive yaw turns
// right and negative pitch looks up, i.e. the engine angles are the negation
// of right-handed angles. Order/signs are configurable (and flippable in the
// in-game settings panel) in case a game build disagrees.

FPV.toGameEuler = function (q, cam) {
    const e = FPV.eulerFromQuat(q, cam.eulerOrder);
    return { x: e.x * cam.pitchSign, y: e.y * cam.yawSign, z: e.z * cam.rollSign };
};

FPV.fromGameYaw = function (gameYaw, cam) {
    return FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, gameYaw * cam.yawSign);
};

FPV.wrapAngle = function (a) {
    while (a > Math.PI) { a -= 2 * Math.PI; }
    while (a < -Math.PI) { a += 2 * Math.PI; }
    return a;
};

// ===== physics.js =====
// ---------------------------------------------------------------------------
// physics.js - a small rigid-body quadcopter model with a Betaflight-style
// rate controller. Pure JS, no game API calls: the client feeds it stick input
// and an environment (floor height lookup) and reads back position/attitude.
// ---------------------------------------------------------------------------

// Defaults approximate a 5" 4S freestyle quad. All of these can be overridden
// from the in-game settings panel or the server config.
FPV.DEFAULT_TUNE = {
    massKg: 0.65,
    gravity: 9.81,
    thrustToWeight: 7.0,
    motorTau: 0.03,          // s, motor/prop spool time constant
    rateTau: 0.022,          // s, how quickly the PID loop reaches the commanded rate
    idleThrottle: 0.045,     // airmode idle - thrust fraction while armed at zero throttle
    dragLinear: 0.015,       // N per m/s
    dragBody: { x: 0.014, y: 0.045, z: 0.010 }, // quadratic, N per (m/s)^2, body axes
    rates: {
        roll: { rcRate: 1.0, superRate: 0.70, expo: 0.0 },
        pitch: { rcRate: 1.0, superRate: 0.70, expo: 0.0 },
        yaw: { rcRate: 1.0, superRate: 0.65, expo: 0.0 }
    },
    throttleMid: 0.5,
    throttleExpo: 0.0,
    angleMaxDeg: 55,
    angleGain: 8.0,          // rad/s of correction per rad of attitude error
    altHoldMaxClimb: 6.0,    // m/s at full stick in "assist" throttle mode
    altHoldGain: 3.0,
    cameraTiltDeg: 25,
    cameraOffset: { x: 0, y: 0.03, z: -0.06 },
    collisionRadius: 0.15,
    crashSpeed: 8.0,         // m/s impact speed that breaks the quad
    groundFriction: 6.0,
    battery: { enabled: true, cells: 4, capacityMah: 1500, maxCurrentA: 120 }
};

FPV.cloneTune = function (t) { return JSON.parse(JSON.stringify(t)); };

// Recursively copies known keys from `src` onto `dst` (ignores unknown keys and
// type mismatches so a stale/garbled settings blob cannot break the model).
FPV.mergeTune = function (dst, src) {
    if (!src || typeof src !== 'object') { return dst; }
    for (const k in dst) {
        if (!Object.prototype.hasOwnProperty.call(src, k)) { continue; }
        if (dst[k] && typeof dst[k] === 'object') {
            FPV.mergeTune(dst[k], src[k]);
        } else if (typeof dst[k] === typeof src[k]) {
            if (typeof src[k] === 'number' && !isFinite(src[k])) { continue; }
            dst[k] = src[k];
        }
    }
    return dst;
};

// Betaflight "actual" rate curve (RC rate / super rate / expo) -> deg/s.
FPV.bfRate = function (stick, r) {
    let rc = FPV.clamp(stick, -1, 1);
    const abs = Math.abs(rc);
    if (r.expo) { rc = rc * abs * abs * abs * r.expo + rc * (1 - r.expo); }
    let rcRate = r.rcRate;
    if (rcRate > 2) { rcRate += 14.54 * (rcRate - 2); }
    let rate = 200 * rcRate * rc;
    if (r.superRate) { rate *= 1 / FPV.clamp(1 - abs * r.superRate, 0.01, 1); }
    return FPV.clamp(rate, -1998, 1998);
};

// Betaflight throttle mid/expo curve, 0..1 -> 0..1.
FPV.throttleCurve = function (thr, mid, expo) {
    thr = FPV.clamp(thr, 0, 1);
    const tmp = thr - mid;
    const range = tmp > 0 ? 1 - mid : mid;
    if (range <= 0) { return thr; }
    return FPV.clamp(mid + tmp * (1 - expo + expo * (tmp * tmp) / (range * range)), 0, 1);
};

FPV.createState = function (pos, q) {
    return {
        pos: FPV.v3(pos.x, pos.y, pos.z),
        vel: FPV.v3(),
        q: q ? FPV.qNorm(q) : FPV.qIdentity(),
        w: FPV.v3(),            // body rates rad/s (x pitch-up, y yaw-left, z roll-left)
        motor: 0,               // actual thrust fraction 0..1
        armed: false,
        crashed: false,
        crashReason: '',
        onGround: false,
        inWater: false,
        usedMah: 0,
        cellVoltage: 4.2,
        currentA: 0,
        flightTime: 0,
        maxSpeed: 0,
        events: []
    };
};

FPV.yawOf = function (q) {
    return FPV.eulerFromQuat(q, 'YXZ').y;
};

// Desired body rates (rad/s) for the current stick input and flight mode.
FPV.desiredRates = function (s, input, tune) {
    const R = tune.rates;
    const acro = {
        x: -FPV.bfRate(input.pitch, R.pitch) * FPV.DEG,  // stick forward -> nose down
        y: -FPV.bfRate(input.yaw, R.yaw) * FPV.DEG,      // stick right  -> yaw right
        z: -FPV.bfRate(input.roll, R.roll) * FPV.DEG     // stick right  -> roll right
    };
    if (input.mode === 'acro') { return acro; }

    // Self-levelling: target attitude = current heading tilted by stick angle.
    const maxA = tune.angleMaxDeg * FPV.DEG;
    const heading = FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, FPV.yawOf(s.q));
    const tilt = FPV.qMul(
        FPV.qAxisAngle({ x: 1, y: 0, z: 0 }, -input.pitch * maxA),
        FPV.qAxisAngle({ x: 0, y: 0, z: 1 }, -input.roll * maxA));
    const target = FPV.qMul(heading, tilt);
    let err = FPV.qMul(FPV.qConj(s.q), target);
    if (err.w < 0) { err = { x: -err.x, y: -err.y, z: -err.z, w: -err.w }; }
    const aa = FPV.qToAxisAngle(err);
    const level = {
        x: aa.axis.x * aa.angle * tune.angleGain,
        y: acro.y,
        z: aa.axis.z * aa.angle * tune.angleGain
    };
    if (input.mode === 'angle') { return level; }

    // Horizon: level near centre stick, acro at full deflection.
    const k = FPV.clamp(Math.max(Math.abs(input.roll), Math.abs(input.pitch)), 0, 1);
    return {
        x: level.x * (1 - k) + acro.x * k,
        y: acro.y,
        z: level.z * (1 - k) + acro.z * k
    };
};

FPV.motorCommand = function (s, input, tune) {
    if (!s.armed || s.crashed) { return 0; }
    const thrust = FPV.throttleCurve(input.throttle, tune.throttleMid, tune.throttleExpo);
    if (input.altHold && input.mode !== 'acro') {
        // Throttle stick commands a climb rate; centre stick = hover.
        const up = FPV.qRotate(s.q, { x: 0, y: 1, z: 0 });
        const tiltCos = Math.max(up.y, 0.3);
        const vzTarget = (FPV.clamp(input.throttle, 0, 1) - 0.5) * 2 * tune.altHoldMaxClimb;
        const accel = tune.gravity + tune.altHoldGain * (vzTarget - s.vel.y);
        const maxAccel = tune.thrustToWeight * tune.gravity;
        return FPV.clamp(accel / (maxAccel * tiltCos), tune.idleThrottle, 1);
    }
    return tune.idleThrottle + (1 - tune.idleThrottle) * thrust;
};

FPV.updateBattery = function (s, tune, dt) {
    const b = tune.battery;
    if (!b.enabled) { s.cellVoltage = 4.2; s.currentA = 0; return 1; }
    s.currentA = 0.8 + b.maxCurrentA * Math.pow(s.motor, 1.5);
    s.usedMah += s.currentA * dt / 3.6;
    const charge = FPV.clamp(1 - s.usedMah / b.capacityMah, 0, 1);
    // Rough LiPo curve: 4.2V full, plateau ~3.8V, knee below 3.5V.
    const rest = 3.3 + 0.9 * Math.pow(charge, 0.6);
    const packSag = s.currentA * 0.012;              // ~12 mOhm pack resistance
    s.cellVoltage = Math.max(2.8, rest - packSag / b.cells);
    if (charge <= 0) { return 0.3; }
    return 0.75 + 0.25 * FPV.clamp((rest - 3.3) / 0.9, 0, 1);
};

FPV.crash = function (s, reason) {
    if (s.crashed) { return; }
    s.crashed = true;
    s.armed = false;
    s.crashReason = reason;
    s.events.push({ type: 'crash', reason: reason, speed: FPV.len(s.vel) });
};

// Advance the simulation by dt seconds.
//   input: {throttle 0..1, roll/pitch/yaw -1..1, mode 'acro'|'angle'|'horizon', altHold}
//   env:   {floorAt(pos) -> {y, water}}
FPV.step = function (s, input, env, tune, dt) {
    const m = tune.massKg;
    const g = tune.gravity;

    // --- rotation -----------------------------------------------------------
    if (s.armed && !s.crashed) {
        const des = FPV.desiredRates(s, input, tune);
        const k = 1 - Math.exp(-dt / tune.rateTau);
        s.w = FPV.add(s.w, FPV.scale(FPV.sub(des, s.w), k));
    } else if (!s.onGround) {
        // Unpowered tumble: props windmill and slowly damp rotation.
        s.w = FPV.scale(s.w, Math.exp(-dt * 0.8));
    }

    // --- motors / battery ---------------------------------------------------
    const cmd = FPV.motorCommand(s, input, tune);
    s.motor += (cmd - s.motor) * (1 - Math.exp(-dt / tune.motorTau));
    const battFactor = FPV.updateBattery(s, tune, dt);

    // --- forces -------------------------------------------------------------
    const maxThrust = tune.thrustToWeight * m * g;
    const up = FPV.qRotate(s.q, { x: 0, y: 1, z: 0 });
    let force = FPV.scale(up, s.motor * maxThrust * battFactor);
    force.y -= m * g;

    const vb = FPV.qRotate(FPV.qConj(s.q), s.vel);
    const db = tune.dragBody;
    const dragB = {
        x: -db.x * Math.abs(vb.x) * vb.x - tune.dragLinear * vb.x,
        y: -db.y * Math.abs(vb.y) * vb.y - tune.dragLinear * vb.y,
        z: -db.z * Math.abs(vb.z) * vb.z - tune.dragLinear * vb.z
    };
    force = FPV.add(force, FPV.qRotate(s.q, dragB));

    // --- integrate (semi-implicit Euler) -------------------------------------
    s.vel = FPV.add(s.vel, FPV.scale(force, dt / m));
    s.pos = FPV.add(s.pos, FPV.scale(s.vel, dt));
    s.q = FPV.qIntegrateBody(s.q, s.w, dt);

    // --- ground / water -----------------------------------------------------
    const floor = env.floorAt(s.pos);
    const r = tune.collisionRadius;
    s.inWater = false;
    if (s.pos.y - r <= floor.y) {
        const impact = -s.vel.y;
        const horiz = Math.sqrt(s.vel.x * s.vel.x + s.vel.z * s.vel.z);
        if (floor.water) {
            s.inWater = true;
            FPV.crash(s, 'WATER');
            s.pos.y = floor.y - r * 0.5;
            s.vel = FPV.scale(s.vel, 0.2);
            s.w = FPV.v3();
        } else {
            if (impact > tune.crashSpeed || horiz > tune.crashSpeed * 2.5) {
                FPV.crash(s, 'IMPACT');
            }
            s.pos.y = floor.y + r;
            if (s.vel.y < 0) { s.vel.y = 0; }
            if (!s.armed || s.motor < 0.3) {
                const f = Math.exp(-dt * tune.groundFriction);
                s.vel.x *= f; s.vel.z *= f;
                // Settle flat on the ground keeping heading.
                s.w = FPV.v3();
                s.q = FPV.qSlerp(s.q, FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, FPV.yawOf(s.q)), 1 - Math.exp(-dt * 10));
            }
        }
        s.onGround = true;
    } else {
        s.onGround = false;
    }

    if (s.armed) { s.flightTime += dt; }
    const speed = FPV.len(s.vel);
    if (speed > s.maxSpeed) { s.maxSpeed = speed; }
    return s;
};

// Arming checks, mirroring a real flight controller. Returns '' on success or
// the reason arming was refused.
FPV.tryArm = function (s, input) {
    if (s.armed) { return ''; }
    if (input.throttle > 0.06 && !(input.altHold && input.mode !== 'acro')) { return 'THROTTLE'; }
    if (input.altHold && input.mode !== 'acro' && input.throttle > 0.55) { return 'THROTTLE'; }
    if (s.inWater) { return 'WATER'; }
    s.crashed = false;
    s.crashReason = '';
    s.armed = true;
    s.events.push({ type: 'arm' });
    return '';
};

FPV.disarm = function (s) {
    if (!s.armed) { return; }
    s.armed = false;
    s.events.push({ type: 'disarm' });
};

FPV.cameraPose = function (s, tune) {
    const tilt = FPV.qAxisAngle({ x: 1, y: 0, z: 0 }, tune.cameraTiltDeg * FPV.DEG);
    return {
        pos: FPV.add(s.pos, FPV.qRotate(s.q, tune.cameraOffset)),
        q: FPV.qMul(s.q, tilt)
    };
};

// ===== world.js =====
// ---------------------------------------------------------------------------
// world.js - what the drone can collide with.
//
// JC3MP's client API has no physics raycast, so the floor is built from:
//   * sea level (water = crash),
//   * "pads": known-good ground points (the launch spot under your feet,
//     crash sites),
//   * surface samples from jcmp.localPlayer.lookAt - the game's own aim ray.
//     While the camera is detached that ray *may* follow our camera; every
//     sample is checked against the camera ray and discarded if it does not
//     line up, so a game build where lookAt does not follow simply falls back
//     to pads + sea level. In FPV you are almost always looking at the ground
//     ahead of you, so the terrain you are about to fly over gets sampled
//     before you get there.
// ---------------------------------------------------------------------------

FPV.World = function (seaLevel) {
    this.seaLevel = seaLevel;
    this.pads = [];
    this.cells = {};          // "cx:cz" -> [y, ...] surface heights in that cell
    this.cellCount = 0;
    this.cellSize = 2.0;
    this.maxCells = 30000;
    this.probeValid = false;  // did the last lookAt sample line up with our camera?
    this.validSamples = 0;
};

FPV.World.prototype.reset = function () {
    this.pads = [];
    this.cells = {};
    this.cellCount = 0;
};

FPV.World.prototype.addPad = function (x, y, z, radius) {
    this.pads.push({ x: x, y: y, z: z, r: radius });
    if (this.pads.length > 64) { this.pads.shift(); }
};

FPV.World.prototype.cellKey = function (x, z) {
    return Math.floor(x / this.cellSize) + ':' + Math.floor(z / this.cellSize);
};

FPV.World.prototype.addSample = function (p) {
    const key = this.cellKey(p.x, p.z);
    let list = this.cells[key];
    if (!list) {
        if (this.cellCount >= this.maxCells) { this.cells = {}; this.cellCount = 0; }
        list = this.cells[key] = [];
        this.cellCount++;
    }
    for (let i = 0; i < list.length; i++) {
        if (Math.abs(list[i] - p.y) < 1.0) { list[i] = p.y; return; }   // refresh existing layer
    }
    list.push(p.y);
    if (list.length > 4) { list.shift(); }
};

// Highest known surface at or just below `pos` (tolerance lets the quad sit
// on a surface whose sample was a few cm above its contact point).
FPV.World.prototype.floorAt = function (pos) {
    let y = this.seaLevel;
    let water = true;
    const tol = 0.5;

    for (let i = 0; i < this.pads.length; i++) {
        const p = this.pads[i];
        const dx = pos.x - p.x, dz = pos.z - p.z;
        if (dx * dx + dz * dz <= p.r * p.r && p.y <= pos.y + tol && p.y > y) {
            y = p.y; water = false;
        }
    }

    const list = this.cells[this.cellKey(pos.x, pos.z)];
    if (list) {
        for (let i = 0; i < list.length; i++) {
            if (list[i] <= pos.y + tol && list[i] > y) { y = list[i]; water = false; }
        }
    }
    return { y: y, water: water };
};

// Validate a lookAt point against the camera ray. Returns the hit distance
// along the ray, or -1 if the sample does not belong to our camera.
FPV.World.prototype.probe = function (camPos, camFwd, hit) {
    this.probeValid = false;
    if (!hit || !FPV.isFiniteVec(hit)) { return -1; }
    const d = FPV.sub(hit, camPos);
    const dist = FPV.len(d);
    if (dist < 0.05 || dist > 1500) { return -1; }
    const cos = FPV.dot(FPV.scale(d, 1 / dist), camFwd);
    if (cos < 0.9994) { return -1; }   // > ~2 degrees off our view ray
    if (Math.abs(hit.y - this.seaLevel) > 0.05) { this.addSample(hit); }
    this.probeValid = true;
    this.validSamples++;
    return dist;
};

// ===== remote.js =====
// ---------------------------------------------------------------------------
// remote.js - other players' drones: snapshot buffer, interpolation, drawing.
// ---------------------------------------------------------------------------

FPV.INTERP_DELAY_MS = 120;
FPV.REMOTE_TIMEOUT_MS = 4000;

FPV.Remotes = function () {
    this.list = {};   // networkId -> remote
};

FPV.Remotes.prototype.ensure = function (id, name) {
    let r = this.list[id];
    if (!r) {
        r = this.list[id] = { id: id, name: name || ('Pilot ' + id), snaps: [], last: 0, pose: null, armed: false, throttle: 0 };
    }
    if (name) { r.name = name; }
    return r;
};

FPV.Remotes.prototype.remove = function (id) { delete this.list[id]; };
FPV.Remotes.prototype.clear = function () { this.list = {}; };

FPV.Remotes.prototype.push = function (id, now, pos, q, armed, throttle) {
    const r = this.ensure(id);
    r.snaps.push({ t: now, pos: pos, q: FPV.qNorm(q) });
    if (r.snaps.length > 20) { r.snaps.shift(); }
    r.last = now;
    r.armed = armed;
    r.throttle = throttle;
};

// Interpolate every remote to (now - delay). Drops remotes that went quiet.
FPV.Remotes.prototype.update = function (now) {
    const t = now - FPV.INTERP_DELAY_MS;
    for (const id in this.list) {
        const r = this.list[id];
        if (now - r.last > FPV.REMOTE_TIMEOUT_MS) { delete this.list[id]; continue; }
        const s = r.snaps;
        if (s.length === 0) { r.pose = null; continue; }
        if (s.length === 1 || t <= s[0].t) { r.pose = { pos: s[0].pos, q: s[0].q }; continue; }
        let i = 1;
        while (i < s.length && s[i].t < t) { i++; }
        if (i >= s.length) {
            // Ran out of data: extrapolate briefly from the last two snapshots.
            const a = s[s.length - 2], b = s[s.length - 1];
            const span = Math.max(b.t - a.t, 1);
            const k = Math.min((t - b.t) / span, 2);
            r.pose = { pos: FPV.lerp3(b.pos, FPV.add(b.pos, FPV.sub(b.pos, a.pos)), k), q: b.q };
        } else {
            const a = s[i - 1], b = s[i];
            const k = FPV.clamp((t - a.t) / Math.max(b.t - a.t, 1), 0, 1);
            r.pose = { pos: FPV.lerp3(a.pos, b.pos, k), q: FPV.qSlerp(a.q, b.q, k) };
        }
    }
};

// ---- drawing (game API) ----------------------------------------------------

FPV.RemoteRenderer = function () {
    this.ready = false;
    this.size = 0.5;          // drawn a bit larger than a real 5" quad so it is visible
    this.color = new RGBA(255, 255, 255, 255);
    this.nameColor = new RGBA(255, 255, 255, 230);
    this.shadow = new RGBA(0, 0, 0, 200);
    this.armedColor = new RGBA(80, 255, 120, 230);
    this.maxText = new Vector2f(1000, 100);
    this.xAxis = new Vector3f(1, 0, 0);
    try {
        this.texTop = new Texture('package://fpvdrone/textures/drone_top.png');
        this.texSide = new Texture('package://fpvdrone/textures/drone_side.png');
        this.ready = true;
    } catch (e) {
        jcmp.print && jcmp.print('[fpvdrone] could not load textures: ' + e);
    }
};

// 3D pass (GameUpdateRender): textured quads at the interpolated pose.
FPV.RemoteRenderer.prototype.draw3d = function (r, remotes, camPos, modelRotSign) {
    if (!this.ready) { return; }
    const half = this.size / 2;
    const topPos = new Vector3f(-half, -half, 0);
    const topSize = new Vector2f(this.size, this.size);
    const sideH = this.size * 0.25;
    const sidePos = new Vector3f(-half, -sideH / 2, 0);
    const sideSize = new Vector2f(this.size, sideH);
    for (const id in remotes.list) {
        const rm = remotes.list[id];
        if (!rm.pose) { continue; }
        if (FPV.dist(rm.pose.pos, camPos) > 1500) { continue; }
        const aa = FPV.qToAxisAngle(rm.pose.q);
        const pos = new Vector3f(rm.pose.pos.x, rm.pose.pos.y, rm.pose.pos.z);
        const axis = new Vector3f(aa.axis.x, aa.axis.y, aa.axis.z);
        const angle = aa.angle * modelRotSign;
        // Matrices are rebuilt rather than reused in case Matrix ops mutate.
        // Top-down silhouette lying in the body XZ plane...
        r.SetTransform(new Matrix().Translate(pos).Rotate(angle, axis).Rotate(Math.PI / 2, this.xAxis));
        r.DrawTexture(this.texTop, topPos, topSize);
        // ...plus a vertical strip across the body so it is visible edge-on.
        r.SetTransform(new Matrix().Translate(pos).Rotate(angle, axis));
        r.DrawTexture(this.texSide, sidePos, sideSize);
    }
};

// 2D pass (Render): name tag + distance above each drone.
FPV.RemoteRenderer.prototype.draw2d = function (r, remotes, camPos) {
    for (const id in remotes.list) {
        const rm = remotes.list[id];
        if (!rm.pose) { continue; }
        const d = FPV.dist(rm.pose.pos, camPos);
        if (d > 1500) { continue; }
        const p = rm.pose.pos;
        const sp = r.WorldToScreen(new Vector3f(p.x, p.y + 0.6, p.z));
        if (!sp || (sp.x === -1 && sp.y === -1)) { continue; }
        const text = rm.name + '  ' + Math.round(d) + 'm';
        const size = d < 50 ? 22 : 18;
        const m = r.MeasureText(text, size, 'Arial');
        const x = sp.x - m.x / 2, y = sp.y - m.y;
        r.DrawText(text, new Vector3f(x + 1, y + 1, 0.5), this.maxText, this.shadow, size, 'Arial');
        r.DrawText(text, new Vector3f(x, y, 0.5), this.maxText, rm.armed ? this.armedColor : this.nameColor, size, 'Arial');
    }
};

// ===== client.js =====
// ---------------------------------------------------------------------------
// client.js - glue between the simulation and JC3MP: camera, input from the
// UI, networking, remote drones and the OSD feed.
// ---------------------------------------------------------------------------

const STEP = 1 / 240;           // physics substep
const OSD_INTERVAL_MS = 33;
const MODES = ['acro', 'angle', 'horizon'];
const VIEWS = ['fpv', 'chase', 'los'];

// Server-provided config (see packages/fpvdrone/config.js). Defaults here are
// used until the server answers.
const cfg = {
    enabled: true,
    seaLevel: 1024,
    syncRateHz: 20,
    followDistance: 250,
    followDepth: 40,
    videoRange: 2500,
    maxAltitude: 4500,
    tuneOverrides: {}
};

// Local pilot settings (edited in the F8 panel, persisted by the UI).
const settings = {
    tune: FPV.cloneTune(FPV.DEFAULT_TUNE),
    camera: { eulerOrder: 'YXZ', pitchSign: -1, yawSign: -1, rollSign: -1, fovDeg: 92, modelRotSign: 1 },
    mode: 'acro',
    altHold: false,
    view: 'fpv'
};

let tune = FPV.cloneTune(FPV.DEFAULT_TUNE);

let status = 'idle';            // idle | pending | flying
let pendingSince = 0;
let drone = null;
let launch = null;              // {x,y,z} where the pilot is standing
let lastFollow = null;
let lastFrame = 0;
let acc = 0;
let lastSend = 0;
let lastOsd = 0;
let lastFollowCheck = 0;
let lastControlsAssert = 0;
let savedFov = null;
let chatOpen = false;
let menuOpen = false;
let prevCam = null;             // camera pose we set last frame (for lookAt validation)
let chaseYaw = 0;
let videoGlitchUntil = 0;
let armSwitchPrev = null;
let armBlockedReason = '';

const input = { throttle: 0, roll: 0, pitch: 0, yaw: 0, mode: 'acro', altHold: false, source: 'keyboard' };

const world = new FPV.World(cfg.seaLevel);
const remotes = new FPV.Remotes();
const renderer = new FPV.RemoteRenderer();

const ui = new WebUIWindow('fpvdrone', 'package://fpvdrone/ui/index.html',
    new Vector2(jcmp.viewportSize.x, jcmp.viewportSize.y));
ui.autoResize = true;

function log(msg) {
    if (typeof jcmp.print === 'function') { jcmp.print('[fpvdrone] ' + msg); }
}

function notify(text, kind) {
    jcmp.ui.CallEvent('fpv/notify', text, kind || 'info');
}

function toVec3f(v) { return new Vector3f(v.x, v.y, v.z); }
function fromVec3f(v) { return { x: v.x, y: v.y, z: v.z }; }

function rebuildTune() {
    tune = FPV.cloneTune(settings.tune);
    FPV.mergeTune(tune, cfg.tuneOverrides);
}

// ---- start / stop ----------------------------------------------------------

function requestStart() {
    if (status !== 'idle') { return; }
    if (!cfg.enabled) { notify('FPV drones are disabled on this server', 'warn'); return; }
    status = 'pending';
    pendingSince = Date.now();
    jcmp.events.CallRemote('fpv/request_start');
}

function begin() {
    const lp = jcmp.localPlayer;
    launch = fromVec3f(lp.position);
    const heading = FPV.fromGameYaw(lp.camera.rotation.y, settings.camera);
    const fwd = FPV.qRotate(heading, { x: 0, y: 0, z: -1 });

    world.seaLevel = cfg.seaLevel;
    world.reset();
    world.addPad(launch.x, launch.y, launch.z, 4.0);

    rebuildTune();
    const start = FPV.add(launch, { x: fwd.x * 1.5, y: tune.collisionRadius, z: fwd.z * 1.5 });
    drone = FPV.createState(start, heading);
    drone.onGround = true;

    savedFov = lp.camera.fieldOfView;
    lp.frozen = true;
    lp.controlsEnabled = false;
    lp.camera.attachedToPlayer = false;
    lp.camera.fieldOfView = settings.camera.fovDeg * FPV.DEG;
    if (typeof jcmp.ui.HideHud === 'function') { jcmp.ui.HideHud(); }

    lastFollow = { x: launch.x, y: launch.y, z: launch.z };
    lastFrame = Date.now();
    acc = 0;
    prevCam = null;
    chaseYaw = FPV.yawOf(heading);
    armSwitchPrev = null;
    armBlockedReason = '';
    status = 'flying';
    jcmp.ui.CallEvent('fpv/active', true);
    notify('Drone ready - arm to take off (E or your arm switch)', 'info');
}

function end(tellServer) {
    if (status === 'pending') { status = 'idle'; return; }
    if (status !== 'flying') { return; }
    status = 'idle';
    const lp = jcmp.localPlayer;
    lp.camera.attachedToPlayer = true;
    if (savedFov !== null) { lp.camera.fieldOfView = savedFov; }
    lp.frozen = false;
    lp.controlsEnabled = !chatOpen && !menuOpen;
    if (typeof jcmp.ui.ShowHud === 'function') { jcmp.ui.ShowHud(); }
    drone = null;
    jcmp.ui.CallEvent('fpv/active', false);
    if (tellServer) { jcmp.events.CallRemote('fpv/stop'); }
}

function resetDrone() {
    if (!drone || !launch) { return; }
    const heading = FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, FPV.yawOf(drone.q));
    const fwd = FPV.qRotate(heading, { x: 0, y: 0, z: -1 });
    drone = FPV.createState(FPV.add(launch, { x: fwd.x * 1.5, y: tune.collisionRadius, z: fwd.z * 1.5 }), heading);
    drone.onGround = true;
    armSwitchPrev = null;
    jcmp.events.CallRemote('fpv/follow', launch.x, launch.y, launch.z, 1);
    lastFollow = { x: launch.x, y: launch.y, z: launch.z };
    notify('Drone reset to launch point', 'info');
}

// ---- arming / commands -----------------------------------------------------

function armRequest(on) {
    if (!drone) { return; }
    if (!on) { FPV.disarm(drone); return; }
    const reason = FPV.tryArm(drone, input);
    if (reason) {
        armBlockedReason = reason;
        notify(reason === 'THROTTLE' ? 'Arming blocked: lower the throttle' :
            reason === 'WATER' ? 'Drone is in the water - press R to reset' : 'Arming blocked: ' + reason, 'warn');
    } else {
        armBlockedReason = '';
    }
}

function command(name) {
    if (chatOpen) { return; }
    switch (name) {
        case 'toggle':
            if (status === 'flying') { end(true); } else { requestStart(); }
            break;
        case 'arm':
            if (drone) { armRequest(!drone.armed); }
            break;
        case 'reset':
            resetDrone();
            break;
        case 'mode':
            settings.mode = MODES[(MODES.indexOf(settings.mode) + 1) % MODES.length];
            jcmp.ui.CallEvent('fpv/mode_changed', settings.mode, settings.altHold);
            break;
        case 'althold':
            settings.altHold = !settings.altHold;
            jcmp.ui.CallEvent('fpv/mode_changed', settings.mode, settings.altHold);
            break;
        case 'view':
            settings.view = VIEWS[(VIEWS.indexOf(settings.view) + 1) % VIEWS.length];
            jcmp.ui.CallEvent('fpv/view_changed', settings.view);
            break;
    }
}

// ---- camera ----------------------------------------------------------------

function lookRotation(dir) {
    const n = FPV.norm(dir);
    const yaw = Math.atan2(-n.x, -n.z);
    const pitch = Math.asin(FPV.clamp(n.y, -1, 1));
    return FPV.qMul(FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, yaw), FPV.qAxisAngle({ x: 1, y: 0, z: 0 }, pitch));
}

function cameraFor(view, dt) {
    if (view === 'chase') {
        const target = FPV.yawOf(drone.q);
        chaseYaw += FPV.wrapAngle(target - chaseYaw) * (1 - Math.exp(-dt * 4));
        const h = FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, chaseYaw);
        const back = FPV.qRotate(h, { x: 0, y: 0, z: 3.0 });
        const pos = FPV.add(drone.pos, { x: back.x, y: 1.0, z: back.z });
        return { pos: pos, q: lookRotation(FPV.sub(drone.pos, pos)) };
    }
    if (view === 'los') {
        const eye = FPV.add(launch, { x: 0, y: 1.7, z: 0 });
        const d = FPV.sub(drone.pos, eye);
        return { pos: eye, q: FPV.len(d) > 0.5 ? lookRotation(d) : FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, FPV.yawOf(drone.q)) };
    }
    return FPV.cameraPose(drone, tune);
}

function applyCamera(cam) {
    const c = jcmp.localPlayer.camera;
    const e = FPV.toGameEuler(cam.q, settings.camera);
    c.position = toVec3f(cam.pos);
    c.rotation = new Vector3f(e.x, e.y, e.z);
}

// ---- per-frame -------------------------------------------------------------

function crashFeedback(ev) {
    videoGlitchUntil = Date.now() + 600;
    jcmp.events.CallRemote('fpv/crash', ev.reason);
}

function probeTerrain(dt) {
    if (!prevCam) { return; }
    let hit = null;
    try { hit = jcmp.localPlayer.lookAt; } catch (e) { hit = null; }
    if (!hit) { return; }
    const camFwd = FPV.qRotate(prevCam.q, { x: 0, y: 0, z: -1 });
    const dist = world.probe(prevCam.pos, camFwd, fromVec3f(hit));
    if (dist < 0 || settings.view !== 'fpv' || drone.crashed) { return; }

    // Head-on obstacle check along the camera ray.
    const along = FPV.dot(drone.vel, camFwd);
    const reach = tune.collisionRadius + 0.2 + Math.max(along, 0) * dt * 1.5;
    if (along > 1.5 && dist < reach) {
        const h = fromVec3f(hit);
        drone.pos = FPV.sub(h, FPV.scale(camFwd, tune.collisionRadius + 0.05));
        if (along > tune.crashSpeed) {
            FPV.crash(drone, 'IMPACT');
            drone.vel = FPV.scale(drone.vel, -0.1);
            // Looking down at what we hit -> it is ground, rest on it. A wall
            // hit lets the wreck drop to whatever floor is known below.
            if (camFwd.y < -0.5) { world.addPad(h.x, h.y, h.z, 1.5); }
        } else {
            // Gentle bump: bounce off, stay armed.
            drone.vel = FPV.sub(drone.vel, FPV.scale(camFwd, along * 1.4));
            drone.events.push({ type: 'bump' });
        }
    }
}

function sendState(now) {
    if (now - lastSend < 1000 / cfg.syncRateHz) { return; }
    lastSend = now;
    const p = drone.pos, q = drone.q;
    jcmp.events.CallRemote('fpv/state', p.x, p.y, p.z, q.x, q.y, q.z, q.w, drone.armed ? 1 : 0, drone.motor);
}

function followCheck(now) {
    // The world streams around the (frozen) character, so drag it along
    // underneath the drone when we get far away.
    if (now - lastFollowCheck < 1000) { return; }
    lastFollowCheck = now;
    const dx = drone.pos.x - lastFollow.x, dz = drone.pos.z - lastFollow.z;
    if (dx * dx + dz * dz > cfg.followDistance * cfg.followDistance) {
        jcmp.events.CallRemote('fpv/follow', drone.pos.x, drone.pos.y, drone.pos.z, 0);
        lastFollow = { x: drone.pos.x, y: drone.pos.y, z: drone.pos.z };
    }
}

function sendOsd(now) {
    if (now - lastOsd < OSD_INTERVAL_MS) { return; }
    lastOsd = now;
    const fwd = FPV.qRotate(drone.q, { x: 0, y: 0, z: -1 });
    const right = FPV.qRotate(drone.q, { x: 1, y: 0, z: 0 });
    const toHome = FPV.sub(launch, drone.pos);
    const distHome = Math.sqrt(toHome.x * toHome.x + toHome.z * toHome.z);
    const homeYaw = Math.atan2(-toHome.x, -toHome.z);
    const vr = cfg.videoRange;
    let noise = FPV.clamp((FPV.dist(launch, drone.pos) - vr * 0.75) / (vr * 0.25), 0, 1);
    if (now < videoGlitchUntil) { noise = Math.max(noise, (videoGlitchUntil - now) / 600); }
    jcmp.ui.CallEvent('fpv/osd', JSON.stringify({
        armed: drone.armed,
        crashed: drone.crashed,
        reason: drone.crashReason,
        blocked: armBlockedReason,
        mode: settings.mode,
        altHold: settings.altHold,
        view: settings.view,
        thr: input.throttle,
        motor: drone.motor,
        speed: FPV.len(drone.vel) * 3.6,
        vspeed: drone.vel.y,
        alt: drone.pos.y - launch.y,
        asl: drone.pos.y - cfg.seaLevel,
        home: distHome,
        homeDir: FPV.wrapAngle(homeYaw - FPV.yawOf(drone.q)),
        pitch: Math.asin(FPV.clamp(fwd.y, -1, 1)),
        roll: Math.asin(FPV.clamp(-right.y, -1, 1)),
        tilt: tune.cameraTiltDeg,
        cell: drone.cellVoltage,
        cells: tune.battery.cells,
        mah: drone.usedMah,
        cap: tune.battery.capacityMah,
        batt: tune.battery.enabled,
        amps: drone.currentA,
        time: drone.flightTime,
        noise: noise,
        probe: world.probeValid,
        src: input.source
    }));
}

function frame(r) {
    const now = Date.now();

    if (status === 'pending' && now - pendingSince > 4000) {
        status = 'idle';
        notify('Server did not answer the FPV request', 'warn');
    }

    remotes.update(now);
    const camPos = fromVec3f(jcmp.localPlayer.camera.position);
    renderer.draw3d(r, remotes, camPos, settings.camera.modelRotSign);

    if (status !== 'flying' || !drone) { return; }

    let dt = (now - lastFrame) / 1000;
    lastFrame = now;
    if (!(dt > 0)) { dt = 0; }
    if (dt > 0.1) { dt = 0.1; }   // hitch / alt-tab: don't explode

    input.mode = settings.mode;
    input.altHold = settings.altHold;

    acc += dt;
    while (acc >= STEP) {
        FPV.step(drone, input, world, tune, STEP);
        acc -= STEP;
    }
    if (drone.pos.y > cfg.maxAltitude) { drone.pos.y = cfg.maxAltitude; if (drone.vel.y > 0) { drone.vel.y = 0; } }

    probeTerrain(dt);

    while (drone.events.length) {
        const ev = drone.events.shift();
        if (ev.type === 'crash') { crashFeedback(ev); }
    }

    const cam = cameraFor(settings.view, dt);
    applyCamera(cam);
    prevCam = cam;

    if (now - lastControlsAssert > 500) {
        lastControlsAssert = now;
        jcmp.localPlayer.controlsEnabled = false;
    }

    sendState(now);
    followCheck(now);
    sendOsd(now);
}

// ---- events: game ----------------------------------------------------------

jcmp.events.Add('GameUpdateRender', (r) => {
    try { frame(r); } catch (e) { log('frame error: ' + (e && e.stack ? e.stack : e)); }
});

jcmp.events.Add('Render', (r) => {
    try {
        renderer.draw2d(r, remotes, fromVec3f(jcmp.localPlayer.camera.position));
    } catch (e) { log('render error: ' + e); }
});

// ---- events: UI ------------------------------------------------------------

jcmp.ui.AddEvent('fpv/ui/ready', () => {
    jcmp.events.CallRemote('fpv/ready');
});

jcmp.ui.AddEvent('fpv/ui/cmd', (name) => { command(name); });

jcmp.ui.AddEvent('fpv/ui/menu', (open) => {
    menuOpen = !!open;
    if (status !== 'flying') { jcmp.localPlayer.controlsEnabled = !menuOpen && !chatOpen; }
});

// Sticks arrive already mapped/calibrated by the UI (gamepad or keyboard).
// arm/mode are -2 when the pilot has not mapped a switch.
jcmp.ui.AddEvent('fpv/ui/sticks', (t, roll, pitch, yaw, arm, mode, source) => {
    input.throttle = FPV.clamp(+t || 0, 0, 1);
    input.roll = FPV.clamp(+roll || 0, -1, 1);
    input.pitch = FPV.clamp(+pitch || 0, -1, 1);
    input.yaw = FPV.clamp(+yaw || 0, -1, 1);
    input.source = source;
    if (!drone || chatOpen) { return; }

    if (arm > -1.5) {
        const on = arm > 0.5;
        if (armSwitchPrev !== null && on !== armSwitchPrev) { armRequest(on); }
        armSwitchPrev = on;
        if (!on && drone.armed) { FPV.disarm(drone); }
    }
    if (mode > -1.5) {
        const m = mode < -0.33 ? 'acro' : (mode > 0.33 ? 'angle' : 'horizon');
        if (m !== settings.mode) {
            settings.mode = m;
            jcmp.ui.CallEvent('fpv/mode_changed', settings.mode, settings.altHold);
        }
    }
});

jcmp.ui.AddEvent('fpv/ui/settings', (json) => {
    let s;
    try { s = JSON.parse(json); } catch (e) { return; }
    if (!s || typeof s !== 'object') { return; }
    if (s.tune) { FPV.mergeTune(settings.tune, s.tune); }
    if (s.camera) {
        const c = settings.camera;
        if (['XYZ', 'YXZ', 'ZXY', 'ZYX', 'YZX', 'XZY'].indexOf(s.camera.eulerOrder) >= 0) { c.eulerOrder = s.camera.eulerOrder; }
        ['pitchSign', 'yawSign', 'rollSign', 'modelRotSign'].forEach((k) => {
            if (s.camera[k] === 1 || s.camera[k] === -1) { c[k] = s.camera[k]; }
        });
        if (isFinite(s.camera.fovDeg)) { c.fovDeg = FPV.clamp(+s.camera.fovDeg, 40, 150); }
    }
    if (MODES.indexOf(s.mode) >= 0) { settings.mode = s.mode; }
    if (typeof s.altHold === 'boolean') { settings.altHold = s.altHold; }
    if (VIEWS.indexOf(s.view) >= 0) { settings.view = s.view; }
    rebuildTune();
    if (status === 'flying') { jcmp.localPlayer.camera.fieldOfView = settings.camera.fovDeg * FPV.DEG; }
});

// Other packages' chat (chat / chat2) broadcast this while the input box is open.
jcmp.ui.AddEvent('chat_input_state', (s) => {
    chatOpen = !!s;
    jcmp.ui.CallEvent('fpv/chat', chatOpen);
});

// ---- events: server --------------------------------------------------------

jcmp.events.AddRemoteCallable('fpv/config', (json) => {
    try {
        const c = JSON.parse(json);
        for (const k in cfg) {
            if (Object.prototype.hasOwnProperty.call(c, k) && typeof c[k] === typeof cfg[k]) { cfg[k] = c[k]; }
        }
        world.seaLevel = cfg.seaLevel;
        rebuildTune();
        jcmp.ui.CallEvent('fpv/config', JSON.stringify(cfg));
    } catch (e) { log('bad config: ' + e); }
});

jcmp.events.AddRemoteCallable('fpv/toggle', () => {
    if (status === 'flying') { end(true); } else { requestStart(); }
});

jcmp.events.AddRemoteCallable('fpv/start', () => {
    if (status === 'pending') { begin(); }
});

jcmp.events.AddRemoteCallable('fpv/denied', (reason) => {
    if (status === 'pending') { status = 'idle'; }
    notify(reason, 'warn');
});

jcmp.events.AddRemoteCallable('fpv/force_stop', (reason) => {
    end(false);
    if (reason) { notify(reason, 'warn'); }
});

jcmp.events.AddRemoteCallable('fpv/remote_start', (id, name) => {
    if (id === jcmp.localPlayer.networkId) { return; }
    remotes.ensure(id, name).last = Date.now();
});

jcmp.events.AddRemoteCallable('fpv/remote_stop', (id) => { remotes.remove(id); });

jcmp.events.AddRemoteCallable('fpv/remote_state', (id, x, y, z, qx, qy, qz, qw, armed, motor) => {
    if (id === jcmp.localPlayer.networkId) { return; }
    remotes.push(id, Date.now(), { x: x, y: y, z: z }, { x: qx, y: qy, z: qz, w: qw }, !!armed, motor);
});

jcmp.events.AddRemoteCallable('fpv/remote_crash', (name, reason) => {
    jcmp.ui.CallEvent('fpv/feed', name + (reason === 'WATER' ? ' ditched in the sea' : ' crashed'));
});

})();
