// GENERATED by tools/build.js from src/client/ - edit those files, then run `npm run build`.
(function () {
const FPV = {};

// ===== math.js =====
// ---------------------------------------------------------------------------
// math.js - vector / quaternion helpers.
//
// Everything here works on plain {x, y, z} / {x, y, z, w} objects so it can be
// unit-tested in Node without the JC3MP runtime. Conversion to the game's
// Vector3f happens only at the edges (client.js / remote.js).
//
// Frames (right-handed, Y up - matches JC3 world space):
//   world: +X east, +Y up, +Z south
//   body : +X right, +Y up, -Z forward (nose)
// ---------------------------------------------------------------------------

FPV.v3 = function (x, y, z) { return { x: x || 0, y: y || 0, z: z || 0 }; };
FPV.add = function (a, b) { return { x: a.x + b.x, y: a.y + b.y, z: a.z + b.z }; };
FPV.sub = function (a, b) { return { x: a.x - b.x, y: a.y - b.y, z: a.z - b.z }; };
FPV.scale = function (a, s) { return { x: a.x * s, y: a.y * s, z: a.z * s }; };
FPV.dot = function (a, b) { return a.x * b.x + a.y * b.y + a.z * b.z; };
FPV.cross = function (a, b) {
    return { x: a.y * b.z - a.z * b.y, y: a.z * b.x - a.x * b.z, z: a.x * b.y - a.y * b.x };
};
FPV.len = function (a) { return Math.sqrt(a.x * a.x + a.y * a.y + a.z * a.z); };
FPV.dist = function (a, b) { return FPV.len(FPV.sub(a, b)); };
FPV.norm = function (a) {
    const l = FPV.len(a);
    return l > 1e-9 ? FPV.scale(a, 1 / l) : { x: 0, y: 0, z: 0 };
};
FPV.lerp3 = function (a, b, t) {
    return { x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t, z: a.z + (b.z - a.z) * t };
};
FPV.clamp = function (v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); };
FPV.isFiniteVec = function (a) {
    return a && isFinite(a.x) && isFinite(a.y) && isFinite(a.z);
};

FPV.DEG = Math.PI / 180;

// ---- quaternions (Hamilton, q = w + xi + yj + zk) --------------------------

FPV.qIdentity = function () { return { x: 0, y: 0, z: 0, w: 1 }; };

FPV.qMul = function (a, b) {
    return {
        w: a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z,
        x: a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y,
        y: a.w * b.y - a.x * b.z + a.y * b.w + a.z * b.x,
        z: a.w * b.z + a.x * b.y - a.y * b.x + a.z * b.w
    };
};

FPV.qConj = function (q) { return { x: -q.x, y: -q.y, z: -q.z, w: q.w }; };

FPV.qNorm = function (q) {
    const l = Math.sqrt(q.x * q.x + q.y * q.y + q.z * q.z + q.w * q.w);
    if (l < 1e-12) { return FPV.qIdentity(); }
    return { x: q.x / l, y: q.y / l, z: q.z / l, w: q.w / l };
};

FPV.qAxisAngle = function (axis, angle) {
    const n = FPV.norm(axis);
    const s = Math.sin(angle / 2);
    return { x: n.x * s, y: n.y * s, z: n.z * s, w: Math.cos(angle / 2) };
};

// Rotate vector v by unit quaternion q (body -> world when q is the attitude).
FPV.qRotate = function (q, v) {
    // t = 2 * cross(q.xyz, v); v' = v + w * t + cross(q.xyz, t)
    const tx = 2 * (q.y * v.z - q.z * v.y);
    const ty = 2 * (q.z * v.x - q.x * v.z);
    const tz = 2 * (q.x * v.y - q.y * v.x);
    return {
        x: v.x + q.w * tx + (q.y * tz - q.z * ty),
        y: v.y + q.w * ty + (q.z * tx - q.x * tz),
        z: v.z + q.w * tz + (q.x * ty - q.y * tx)
    };
};

// Integrate body-frame angular velocity w (rad/s) over dt.
FPV.qIntegrateBody = function (q, w, dt) {
    const ang = FPV.len(w) * dt;
    if (ang < 1e-12) { return q; }
    const dq = FPV.qAxisAngle(w, ang);
    return FPV.qNorm(FPV.qMul(q, dq));
};

FPV.qSlerp = function (a, b, t) {
    let bx = b.x, by = b.y, bz = b.z, bw = b.w;
    let cos = a.x * bx + a.y * by + a.z * bz + a.w * bw;
    if (cos < 0) { cos = -cos; bx = -bx; by = -by; bz = -bz; bw = -bw; }
    if (cos > 0.9995) {
        return FPV.qNorm({
            x: a.x + (bx - a.x) * t, y: a.y + (by - a.y) * t,
            z: a.z + (bz - a.z) * t, w: a.w + (bw - a.w) * t
        });
    }
    const theta = Math.acos(cos);
    const s = Math.sin(theta);
    const wa = Math.sin((1 - t) * theta) / s;
    const wb = Math.sin(t * theta) / s;
    return { x: a.x * wa + bx * wb, y: a.y * wa + by * wb, z: a.z * wa + bz * wb, w: a.w * wa + bw * wb };
};

// Returns {axis, angle} for use with the game's Matrix.Rotate(angle, axis).
FPV.qToAxisAngle = function (q) {
    q = FPV.qNorm(q);
    if (q.w < 0) { q = { x: -q.x, y: -q.y, z: -q.z, w: -q.w }; }
    const angle = 2 * Math.acos(FPV.clamp(q.w, -1, 1));
    const s = Math.sqrt(1 - q.w * q.w);
    if (s < 1e-6) { return { axis: { x: 0, y: 1, z: 0 }, angle: 0 }; }
    return { axis: { x: q.x / s, y: q.y / s, z: q.z / s }, angle: angle };
};

// Row-major 3x3 rotation matrix (m[row][col]); columns are the body axes in world.
FPV.qToMat = function (q) {
    const x = q.x, y = q.y, z = q.z, w = q.w;
    return [
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)]
    ];
};

// ---- Euler angles ----------------------------------------------------------
// `order` names the intrinsic rotation sequence, e.g. 'YXZ' means
// R = Ry(e.y) * Rx(e.x) * Rz(e.z)  (yaw, then pitch, then roll).
// Formulas follow three.js Euler.setFromRotationMatrix.

FPV.eulerFromQuat = function (q, order) {
    const m = FPV.qToMat(q);
    const m11 = m[0][0], m12 = m[0][1], m13 = m[0][2];
    const m21 = m[1][0], m22 = m[1][1], m23 = m[1][2];
    const m31 = m[2][0], m32 = m[2][1], m33 = m[2][2];
    const c = FPV.clamp;
    const e = { x: 0, y: 0, z: 0 };
    switch (order) {
        case 'XYZ':
            e.y = Math.asin(c(m13, -1, 1));
            if (Math.abs(m13) < 0.9999999) { e.x = Math.atan2(-m23, m33); e.z = Math.atan2(-m12, m11); }
            else { e.x = Math.atan2(m32, m22); e.z = 0; }
            break;
        case 'YXZ':
            e.x = Math.asin(-c(m23, -1, 1));
            if (Math.abs(m23) < 0.9999999) { e.y = Math.atan2(m13, m33); e.z = Math.atan2(m21, m22); }
            else { e.y = Math.atan2(-m31, m11); e.z = 0; }
            break;
        case 'ZXY':
            e.x = Math.asin(c(m32, -1, 1));
            if (Math.abs(m32) < 0.9999999) { e.y = Math.atan2(-m31, m33); e.z = Math.atan2(-m12, m22); }
            else { e.y = 0; e.z = Math.atan2(m21, m11); }
            break;
        case 'ZYX':
            e.y = Math.asin(-c(m31, -1, 1));
            if (Math.abs(m31) < 0.9999999) { e.x = Math.atan2(m32, m33); e.z = Math.atan2(m21, m11); }
            else { e.x = 0; e.z = Math.atan2(-m12, m22); }
            break;
        case 'YZX':
            e.z = Math.asin(c(m21, -1, 1));
            if (Math.abs(m21) < 0.9999999) { e.x = Math.atan2(-m23, m22); e.y = Math.atan2(-m31, m11); }
            else { e.x = 0; e.y = Math.atan2(m13, m33); }
            break;
        case 'XZY':
            e.z = Math.asin(-c(m12, -1, 1));
            if (Math.abs(m12) < 0.9999999) { e.x = Math.atan2(m32, m22); e.y = Math.atan2(m13, m11); }
            else { e.x = Math.atan2(-m23, m33); e.y = 0; }
            break;
        default:
            throw new Error('Unknown euler order ' + order);
    }
    return e;
};

FPV.quatFromEuler = function (e, order) {
    const X = FPV.qAxisAngle({ x: 1, y: 0, z: 0 }, e.x);
    const Y = FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, e.y);
    const Z = FPV.qAxisAngle({ x: 0, y: 0, z: 1 }, e.z);
    const map = { X: X, Y: Y, Z: Z };
    return FPV.qNorm(FPV.qMul(FPV.qMul(map[order[0]], map[order[1]]), map[order[2]]));
};

// ---- JC3 camera conversion -------------------------------------------------
// JC3MP exposes camera.rotation as a Vector3f of euler angles (x = pitch,
// y = yaw, z = roll). Existing freecam packages show that positive yaw turns
// right and negative pitch looks up, i.e. the engine angles are the negation
// of right-handed angles. Order/signs are configurable (and flippable in the
// in-game settings panel) in case a game build disagrees.

FPV.toGameEuler = function (q, cam) {
    const e = FPV.eulerFromQuat(q, cam.eulerOrder);
    return { x: e.x * cam.pitchSign, y: e.y * cam.yawSign, z: e.z * cam.rollSign };
};

FPV.fromGameYaw = function (gameYaw, cam) {
    return FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, gameYaw * cam.yawSign);
};

FPV.wrapAngle = function (a) {
    while (a > Math.PI) { a -= 2 * Math.PI; }
    while (a < -Math.PI) { a += 2 * Math.PI; }
    return a;
};

// Quaternion from orthonormal body axes expressed in world space
// (columns of the rotation matrix).
FPV.quatFromBasis = function (X, Y, Z) {
    const m00 = X.x, m01 = Y.x, m02 = Z.x;
    const m10 = X.y, m11 = Y.y, m12 = Z.y;
    const m20 = X.z, m21 = Y.z, m22 = Z.z;
    const tr = m00 + m11 + m22;
    let q;
    if (tr > 0) {
        const s = Math.sqrt(tr + 1) * 2;
        q = { w: 0.25 * s, x: (m21 - m12) / s, y: (m02 - m20) / s, z: (m10 - m01) / s };
    } else if (m00 > m11 && m00 > m22) {
        const s = Math.sqrt(1 + m00 - m11 - m22) * 2;
        q = { w: (m21 - m12) / s, x: 0.25 * s, y: (m01 + m10) / s, z: (m02 + m20) / s };
    } else if (m11 > m22) {
        const s = Math.sqrt(1 + m11 - m00 - m22) * 2;
        q = { w: (m02 - m20) / s, x: (m01 + m10) / s, y: 0.25 * s, z: (m12 + m21) / s };
    } else {
        const s = Math.sqrt(1 + m22 - m00 - m11) * 2;
        q = { w: (m10 - m01) / s, x: (m02 + m20) / s, y: (m12 + m21) / s, z: 0.25 * s };
    }
    return FPV.qNorm(q);
};

// Attitude whose forward (-Z) points along `dir`, with no roll.
FPV.lookRotation = function (dir) {
    const n = FPV.norm(dir);
    const yaw = Math.atan2(-n.x, -n.z);
    const pitch = Math.asin(FPV.clamp(n.y, -1, 1));
    return FPV.qMul(FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, yaw), FPV.qAxisAngle({ x: 1, y: 0, z: 0 }, pitch));
};

FPV.clampLen = function (v, max) {
    const l = FPV.len(v);
    return l > max ? FPV.scale(v, max / l) : v;
};

FPV.horiz = function (v) { return { x: v.x, y: 0, z: v.z }; };

// ===== physics.js =====
// ---------------------------------------------------------------------------
// physics.js - a small rigid-body quadcopter model with a Betaflight-style
// rate controller. Pure JS, no game API calls: the client feeds it stick input
// and an environment (floor height lookup) and reads back position/attitude.
// ---------------------------------------------------------------------------

// Defaults approximate a 5" 4S freestyle quad. All of these can be overridden
// from the in-game settings panel or the server config.
FPV.DEFAULT_TUNE = {
    massKg: 0.65,
    gravity: 9.81,
    thrustToWeight: 7.0,
    motorTau: 0.03,          // s, motor/prop spool time constant
    rateTau: 0.022,          // s, how quickly the PID loop reaches the commanded rate
    idleThrottle: 0.045,     // airmode idle - thrust fraction while armed at zero throttle
    dragLinear: 0.015,       // N per m/s
    dragBody: { x: 0.014, y: 0.045, z: 0.010 }, // quadratic, N per (m/s)^2, body axes
    rates: {
        roll: { rcRate: 1.0, superRate: 0.70, expo: 0.0 },
        pitch: { rcRate: 1.0, superRate: 0.70, expo: 0.0 },
        yaw: { rcRate: 1.0, superRate: 0.65, expo: 0.0 }
    },
    throttleMid: 0.5,
    throttleExpo: 0.0,
    angleMaxDeg: 55,
    angleGain: 8.0,          // rad/s of correction per rad of attitude error
    altHoldMaxClimb: 6.0,    // m/s at full stick in "assist" throttle mode
    altHoldGain: 3.0,
    cameraTiltDeg: 25,
    cameraOffset: { x: 0, y: 0.03, z: -0.06 },
    collisionRadius: 0.15,
    crashSpeed: 8.0,         // m/s impact speed that breaks the quad
    groundFriction: 6.0,
    battery: { enabled: true, cells: 4, capacityMah: 1500, maxCurrentA: 120 }
};

FPV.cloneTune = function (t) { return JSON.parse(JSON.stringify(t)); };

// Recursively copies known keys from `src` onto `dst` (ignores unknown keys and
// type mismatches so a stale/garbled settings blob cannot break the model).
FPV.mergeTune = function (dst, src) {
    if (!src || typeof src !== 'object') { return dst; }
    for (const k in dst) {
        if (!Object.prototype.hasOwnProperty.call(src, k)) { continue; }
        if (dst[k] && typeof dst[k] === 'object') {
            FPV.mergeTune(dst[k], src[k]);
        } else if (typeof dst[k] === typeof src[k]) {
            if (typeof src[k] === 'number' && !isFinite(src[k])) { continue; }
            dst[k] = src[k];
        }
    }
    return dst;
};

// Betaflight "actual" rate curve (RC rate / super rate / expo) -> deg/s.
FPV.bfRate = function (stick, r) {
    let rc = FPV.clamp(stick, -1, 1);
    const abs = Math.abs(rc);
    if (r.expo) { rc = rc * abs * abs * abs * r.expo + rc * (1 - r.expo); }
    let rcRate = r.rcRate;
    if (rcRate > 2) { rcRate += 14.54 * (rcRate - 2); }
    let rate = 200 * rcRate * rc;
    if (r.superRate) { rate *= 1 / FPV.clamp(1 - abs * r.superRate, 0.01, 1); }
    return FPV.clamp(rate, -1998, 1998);
};

// Betaflight throttle mid/expo curve, 0..1 -> 0..1.
FPV.throttleCurve = function (thr, mid, expo) {
    thr = FPV.clamp(thr, 0, 1);
    const tmp = thr - mid;
    const range = tmp > 0 ? 1 - mid : mid;
    if (range <= 0) { return thr; }
    return FPV.clamp(mid + tmp * (1 - expo + expo * (tmp * tmp) / (range * range)), 0, 1);
};

FPV.createState = function (pos, q) {
    return {
        pos: FPV.v3(pos.x, pos.y, pos.z),
        vel: FPV.v3(),
        q: q ? FPV.qNorm(q) : FPV.qIdentity(),
        w: FPV.v3(),            // body rates rad/s (x pitch-up, y yaw-left, z roll-left)
        motor: 0,               // actual thrust fraction 0..1
        armed: false,
        crashed: false,
        crashReason: '',
        onGround: false,
        inWater: false,
        usedMah: 0,
        cellVoltage: 4.2,
        currentA: 0,
        flightTime: 0,
        maxSpeed: 0,
        events: []
    };
};

FPV.yawOf = function (q) {
    return FPV.eulerFromQuat(q, 'YXZ').y;
};

// Desired body rates (rad/s) for the current stick input and flight mode.
FPV.desiredRates = function (s, input, tune) {
    if (input.mode === 'direct') { return input.wDes; }   // autopilot (swarm wingmen)
    const R = tune.rates;
    const acro = {
        x: -FPV.bfRate(input.pitch, R.pitch) * FPV.DEG,  // stick forward -> nose down
        y: -FPV.bfRate(input.yaw, R.yaw) * FPV.DEG,      // stick right  -> yaw right
        z: -FPV.bfRate(input.roll, R.roll) * FPV.DEG     // stick right  -> roll right
    };
    if (input.mode === 'acro') { return acro; }

    // Self-levelling: target attitude = current heading tilted by stick angle.
    const maxA = tune.angleMaxDeg * FPV.DEG;
    const heading = FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, FPV.yawOf(s.q));
    const tilt = FPV.qMul(
        FPV.qAxisAngle({ x: 1, y: 0, z: 0 }, -input.pitch * maxA),
        FPV.qAxisAngle({ x: 0, y: 0, z: 1 }, -input.roll * maxA));
    const target = FPV.qMul(heading, tilt);
    let err = FPV.qMul(FPV.qConj(s.q), target);
    if (err.w < 0) { err = { x: -err.x, y: -err.y, z: -err.z, w: -err.w }; }
    const aa = FPV.qToAxisAngle(err);
    const level = {
        x: aa.axis.x * aa.angle * tune.angleGain,
        y: acro.y,
        z: aa.axis.z * aa.angle * tune.angleGain
    };
    if (input.mode === 'angle') { return level; }

    // Horizon: level near centre stick, acro at full deflection.
    const k = FPV.clamp(Math.max(Math.abs(input.roll), Math.abs(input.pitch)), 0, 1);
    return {
        x: level.x * (1 - k) + acro.x * k,
        y: acro.y,
        z: level.z * (1 - k) + acro.z * k
    };
};

FPV.motorCommand = function (s, input, tune) {
    if (!s.armed || s.crashed) { return 0; }
    if (input.mode === 'direct') { return FPV.clamp(input.thrustCmd, tune.idleThrottle, 1); }
    const thrust = FPV.throttleCurve(input.throttle, tune.throttleMid, tune.throttleExpo);
    if (input.altHold && input.mode !== 'acro') {
        // Throttle stick commands a climb rate; centre stick = hover.
        const up = FPV.qRotate(s.q, { x: 0, y: 1, z: 0 });
        const tiltCos = Math.max(up.y, 0.3);
        const vzTarget = (FPV.clamp(input.throttle, 0, 1) - 0.5) * 2 * tune.altHoldMaxClimb;
        const accel = tune.gravity + tune.altHoldGain * (vzTarget - s.vel.y);
        const maxAccel = tune.thrustToWeight * tune.gravity;
        return FPV.clamp(accel / (maxAccel * tiltCos), tune.idleThrottle, 1);
    }
    return tune.idleThrottle + (1 - tune.idleThrottle) * thrust;
};

FPV.updateBattery = function (s, tune, dt) {
    const b = tune.battery;
    if (!b.enabled) { s.cellVoltage = 4.2; s.currentA = 0; return 1; }
    s.currentA = 0.8 + b.maxCurrentA * Math.pow(s.motor, 1.5);
    s.usedMah += s.currentA * dt / 3.6;
    const charge = FPV.clamp(1 - s.usedMah / b.capacityMah, 0, 1);
    // Rough LiPo curve: 4.2V full, plateau ~3.8V, knee below 3.5V.
    const rest = 3.3 + 0.9 * Math.pow(charge, 0.6);
    const packSag = s.currentA * 0.012;              // ~12 mOhm pack resistance
    s.cellVoltage = Math.max(2.8, rest - packSag / b.cells);
    if (charge <= 0) { return 0.3; }
    return 0.75 + 0.25 * FPV.clamp((rest - 3.3) / 0.9, 0, 1);
};

// Aerodynamic drag (world frame, Newtons) for attitude q moving at vel.
FPV.dragForce = function (q, vel, tune) {
    const vb = FPV.qRotate(FPV.qConj(q), vel);
    const db = tune.dragBody;
    return FPV.qRotate(q, {
        x: -db.x * Math.abs(vb.x) * vb.x - tune.dragLinear * vb.x,
        y: -db.y * Math.abs(vb.y) * vb.y - tune.dragLinear * vb.y,
        z: -db.z * Math.abs(vb.z) * vb.z - tune.dragLinear * vb.z
    });
};

FPV.crash = function (s, reason) {
    if (s.crashed) { return; }
    s.crashed = true;
    s.armed = false;
    s.crashReason = reason;
    s.events.push({ type: 'crash', reason: reason, speed: FPV.len(s.vel) });
};

// Advance the simulation by dt seconds.
//   input: {throttle 0..1, roll/pitch/yaw -1..1, mode 'acro'|'angle'|'horizon', altHold}
//   env:   {floorAt(pos) -> {y, water}}
FPV.step = function (s, input, env, tune, dt) {
    const m = tune.massKg;
    const g = tune.gravity;

    // --- rotation -----------------------------------------------------------
    if (s.armed && !s.crashed) {
        const des = FPV.desiredRates(s, input, tune);
        const k = 1 - Math.exp(-dt / tune.rateTau);
        s.w = FPV.add(s.w, FPV.scale(FPV.sub(des, s.w), k));
    } else if (!s.onGround) {
        // Unpowered tumble: props windmill and slowly damp rotation.
        s.w = FPV.scale(s.w, Math.exp(-dt * 0.8));
    }

    // --- motors / battery ---------------------------------------------------
    const cmd = FPV.motorCommand(s, input, tune);
    s.motor += (cmd - s.motor) * (1 - Math.exp(-dt / tune.motorTau));
    const battFactor = FPV.updateBattery(s, tune, dt);

    // --- forces -------------------------------------------------------------
    const maxThrust = tune.thrustToWeight * m * g;
    const up = FPV.qRotate(s.q, { x: 0, y: 1, z: 0 });
    let force = FPV.scale(up, s.motor * maxThrust * battFactor);
    force.y -= m * g;

    force = FPV.add(force, FPV.dragForce(s.q, s.vel, tune));

    // --- integrate (semi-implicit Euler) -------------------------------------
    s.vel = FPV.add(s.vel, FPV.scale(force, dt / m));
    s.pos = FPV.add(s.pos, FPV.scale(s.vel, dt));
    s.q = FPV.qIntegrateBody(s.q, s.w, dt);

    // --- ground / water -----------------------------------------------------
    const floor = env.floorAt(s.pos);
    const r = tune.collisionRadius;
    s.inWater = false;
    if (s.pos.y - r <= floor.y) {
        const impact = -s.vel.y;
        const horiz = Math.sqrt(s.vel.x * s.vel.x + s.vel.z * s.vel.z);
        if (floor.water) {
            s.inWater = true;
            FPV.crash(s, 'WATER');
            s.pos.y = floor.y - r * 0.5;
            s.vel = FPV.scale(s.vel, 0.2);
            s.w = FPV.v3();
        } else {
            if (impact > tune.crashSpeed || horiz > tune.crashSpeed * 2.5) {
                FPV.crash(s, 'IMPACT');
            }
            s.pos.y = floor.y + r;
            if (s.vel.y < 0) { s.vel.y = 0; }
            if (!s.armed || s.motor < 0.3) {
                const f = Math.exp(-dt * tune.groundFriction);
                s.vel.x *= f; s.vel.z *= f;
                // Settle flat on the ground keeping heading.
                s.w = FPV.v3();
                s.q = FPV.qSlerp(s.q, FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, FPV.yawOf(s.q)), 1 - Math.exp(-dt * 10));
            }
        }
        s.onGround = true;
    } else {
        s.onGround = false;
    }

    if (s.armed) { s.flightTime += dt; }
    const speed = FPV.len(s.vel);
    if (speed > s.maxSpeed) { s.maxSpeed = speed; }
    return s;
};

// Arming checks, mirroring a real flight controller. Returns '' on success or
// the reason arming was refused.
FPV.tryArm = function (s, input) {
    if (s.armed) { return ''; }
    if (input.throttle > 0.06 && !(input.altHold && input.mode !== 'acro')) { return 'THROTTLE'; }
    if (input.altHold && input.mode !== 'acro' && input.throttle > 0.55) { return 'THROTTLE'; }
    if (s.inWater) { return 'WATER'; }
    s.crashed = false;
    s.crashReason = '';
    s.armed = true;
    s.events.push({ type: 'arm' });
    return '';
};

FPV.disarm = function (s) {
    if (!s.armed) { return; }
    s.armed = false;
    s.events.push({ type: 'disarm' });
};

FPV.cameraPose = function (s, tune) {
    const tilt = FPV.qAxisAngle({ x: 1, y: 0, z: 0 }, tune.cameraTiltDeg * FPV.DEG);
    return {
        pos: FPV.add(s.pos, FPV.qRotate(s.q, tune.cameraOffset)),
        q: FPV.qMul(s.q, tilt)
    };
};

// ===== world.js =====
// ---------------------------------------------------------------------------
// world.js - what the drone can collide with.
//
// JC3MP's client API has no physics raycast, so the floor is built from:
//   * sea level (water = crash),
//   * "pads": known-good ground points (the launch spot under your feet,
//     crash sites),
//   * surface samples from jcmp.localPlayer.lookAt - the game's own aim ray.
//     While the camera is detached that ray *may* follow our camera; every
//     sample is checked against the camera ray and discarded if it does not
//     line up, so a game build where lookAt does not follow simply falls back
//     to pads + sea level. In FPV you are almost always looking at the ground
//     ahead of you, so the terrain you are about to fly over gets sampled
//     before you get there.
// ---------------------------------------------------------------------------

FPV.World = function (seaLevel) {
    this.seaLevel = seaLevel;
    this.pads = [];
    this.cells = {};          // "cx:cz" -> [y, ...] surface heights in that cell
    this.cellCount = 0;
    this.cellSize = 2.0;
    this.maxCells = 30000;
    this.probeValid = false;  // did the last lookAt sample line up with our camera?
    this.validSamples = 0;
};

FPV.World.prototype.reset = function () {
    this.pads = [];
    this.cells = {};
    this.cellCount = 0;
};

FPV.World.prototype.addPad = function (x, y, z, radius) {
    this.pads.push({ x: x, y: y, z: z, r: radius });
    if (this.pads.length > 64) { this.pads.shift(); }
};

FPV.World.prototype.cellKey = function (x, z) {
    return Math.floor(x / this.cellSize) + ':' + Math.floor(z / this.cellSize);
};

FPV.World.prototype.addSample = function (p) {
    const key = this.cellKey(p.x, p.z);
    let list = this.cells[key];
    if (!list) {
        if (this.cellCount >= this.maxCells) { this.cells = {}; this.cellCount = 0; }
        list = this.cells[key] = [];
        this.cellCount++;
    }
    for (let i = 0; i < list.length; i++) {
        if (Math.abs(list[i] - p.y) < 1.0) { list[i] = p.y; return; }   // refresh existing layer
    }
    list.push(p.y);
    if (list.length > 4) { list.shift(); }
};

// Highest known surface at or just below `pos` (tolerance lets the quad sit
// on a surface whose sample was a few cm above its contact point).
FPV.World.prototype.floorAt = function (pos) {
    let y = this.seaLevel;
    let water = true;
    const tol = 0.5;

    for (let i = 0; i < this.pads.length; i++) {
        const p = this.pads[i];
        const dx = pos.x - p.x, dz = pos.z - p.z;
        if (dx * dx + dz * dz <= p.r * p.r && p.y <= pos.y + tol && p.y > y) {
            y = p.y; water = false;
        }
    }

    const list = this.cells[this.cellKey(pos.x, pos.z)];
    if (list) {
        for (let i = 0; i < list.length; i++) {
            if (list[i] <= pos.y + tol && list[i] > y) { y = list[i]; water = false; }
        }
    }
    return { y: y, water: water };
};

// Validate a lookAt point against the camera ray. Returns the hit distance
// along the ray, or -1 if the sample does not belong to our camera.
FPV.World.prototype.probe = function (camPos, camFwd, hit) {
    this.probeValid = false;
    if (!hit || !FPV.isFiniteVec(hit)) { return -1; }
    const d = FPV.sub(hit, camPos);
    const dist = FPV.len(d);
    if (dist < 0.05 || dist > 1500) { return -1; }
    const cos = FPV.dot(FPV.scale(d, 1 / dist), camFwd);
    if (cos < 0.9994) { return -1; }   // > ~2 degrees off our view ray
    if (Math.abs(hit.y - this.seaLevel) > 0.05) { this.addSample(hit); }
    this.probeValid = true;
    this.validSamples++;
    return dist;
};

// ===== swarm.js =====
// ---------------------------------------------------------------------------
// swarm.js - AI wingmen that fly the same physics model as the player.
//
// Behaviours (per wingman `role`):
//   join   - fly to a slot in a dynamic formation around the controlled drone:
//            a wedge behind it when it is moving, a slow ring when it hovers.
//   orbit  - "support": circle the point the player is diving at, at least
//            `orbitMinHeight` above it, cameras facing the centre, so one of
//            them can take over straight after the player's drone impacts.
//   attack - pursue and ram an assigned target (proportional lead).
//   aim    - handover: pitch so the FPV camera points at a spot, then the
//            client gives this drone to the player.
//   wreck  - crashed; falls and is removed after a while.
//
// All pure JS: the client supplies the leader state, a floor lookup and a
// target list; the swarm returns events (impacts, losses).
// ---------------------------------------------------------------------------

FPV.SWARM_DEFAULTS = {
    maxWingmen: 5,
    formationMinHeight: 4,   // m above known ground while in formation
    orbitMinHeight: 25,      // m above the attack point while circling
    orbitRadius: 35,
    orbitSpeed: 11,          // m/s tangential
    cruiseSpeed: 45,         // m/s max transit speed
    attackSpeed: 40,
    attackRadius: 150,       // targets are picked within this range of the leader
    hitRadius: 2.2,
    wreckSeconds: 15,
    impactMinSpeed: 10       // m/s - slower crashes do no damage
};

FPV.SWARM_STEP = 1 / 120;

// Turn a guidance command into direct rate/thrust input for FPV.step.
//   cmd.vel        desired world velocity
//   cmd.face       world direction the nose (or camera, with aimCamera) should face
//   cmd.aimCamera  point the tilted FPV camera along cmd.face instead of the nose
//   cmd.aimThrust  thrust fraction to hold while aiming
FPV.autopilot = function (s, cmd, tune) {
    const g = tune.gravity;
    const maxAcc = tune.thrustToWeight * g;
    let qDes;
    let thrust;

    if (cmd.aimCamera) {
        const tilt = FPV.qAxisAngle({ x: 1, y: 0, z: 0 }, -tune.cameraTiltDeg * FPV.DEG);
        qDes = FPV.qMul(FPV.lookRotation(cmd.face), tilt);
        thrust = cmd.aimThrust !== undefined ? cmd.aimThrust : 1 / tune.thrustToWeight;
    } else {
        let a = FPV.scale(FPV.sub(cmd.vel, s.vel), cmd.velGain || 2.5);
        // Feed-forward the drag we will meet at the commanded speed.
        a = FPV.sub(a, FPV.scale(FPV.dragForce(s.q, cmd.vel, tune), 1 / tune.massKg));
        const aMax = cmd.maxAccel || 24;
        const ah = Math.sqrt(a.x * a.x + a.z * a.z);
        if (ah > aMax) { a.x *= aMax / ah; a.z *= aMax / ah; }
        const f = { x: a.x, y: FPV.clamp(a.y, -0.75 * g, maxAcc) + g, z: a.z };
        const maxTilt = (cmd.maxTiltDeg || 60) * FPV.DEG;
        const fh = Math.sqrt(f.x * f.x + f.z * f.z);
        if (fh > 1e-6 && Math.atan2(fh, f.y) > maxTilt) {
            const k = f.y * Math.tan(maxTilt) / fh;
            f.x *= k; f.z *= k;
        }
        const fl = FPV.len(f);
        const up = FPV.scale(f, 1 / fl);
        thrust = fl / maxAcc;

        let fwd = cmd.face && FPV.len(FPV.horiz(cmd.face)) > 1e-3 ? cmd.face : FPV.qRotate(s.q, { x: 0, y: 0, z: -1 });
        let proj = FPV.sub(fwd, FPV.scale(up, FPV.dot(fwd, up)));
        if (FPV.len(proj) < 1e-3) { proj = FPV.qRotate(s.q, { x: 0, y: 0, z: -1 }); }
        const Z = FPV.scale(FPV.norm(proj), -1);
        const X = FPV.norm(FPV.cross(up, Z));
        qDes = FPV.quatFromBasis(X, up, FPV.cross(X, up));
    }

    let err = FPV.qMul(FPV.qConj(s.q), qDes);
    if (err.w < 0) { err = { x: -err.x, y: -err.y, z: -err.z, w: -err.w }; }
    const aa = FPV.qToAxisAngle(err);
    const gain = 9;
    const w = FPV.clampLen(FPV.scale(aa.axis, aa.angle * gain), 14);
    return { mode: 'direct', wDes: w, thrustCmd: FPV.clamp(thrust, 0, 1), throttle: 0, roll: 0, pitch: 0, yaw: 0 };
};

FPV.Swarm = function (opts, tune) {
    this.opts = {};
    for (const k in FPV.SWARM_DEFAULTS) { this.opts[k] = FPV.SWARM_DEFAULTS[k]; }
    this.configure(opts);
    this.setTune(tune || FPV.DEFAULT_TUNE);
    this.wingmen = [];
    this.nextId = 1;
    this.mode = 'formation';     // formation | support
    this.center = null;          // support orbit centre
    this.supportSince = 0;
    this.diveTime = 0;
    this.time = 0;
    this.acc = 0;
    this.events = [];
};

FPV.Swarm.prototype.configure = function (opts) {
    if (!opts) { return; }
    for (const k in this.opts) {
        if (typeof opts[k] === 'number' && isFinite(opts[k])) { this.opts[k] = opts[k]; }
    }
};

FPV.Swarm.prototype.setTune = function (tune) {
    this.tune = FPV.cloneTune(tune);
    this.tune.battery.enabled = false;   // wingmen don't run out mid-fight
};

FPV.Swarm.prototype.flying = function () {
    return this.wingmen.filter(function (w) { return w.role !== 'wreck'; });
};

FPV.Swarm.prototype.attackers = function () {
    return this.wingmen.filter(function (w) { return w.role === 'attack'; });
};

FPV.Swarm.prototype.add = function (state, role, id) {
    const w = {
        id: id !== undefined ? id : this.nextId++,
        s: state,
        role: role || 'join',
        target: null,
        aimPoint: null,
        phase: Math.random() * Math.PI * 2,
        age: 0,
        input: null
    };
    if (w.id >= this.nextId) { this.nextId = w.id + 1; }
    this.wingmen.push(w);
    return w;
};

// Launch a new wingman from `pos` (it takes off and flies to the formation).
FPV.Swarm.prototype.spawn = function (pos, q) {
    if (this.flying().length >= this.opts.maxWingmen) { return null; }
    const s = FPV.createState(pos, q);
    s.armed = true;
    s.onGround = true;
    return this.add(s, 'join');
};

FPV.Swarm.prototype.remove = function (w) {
    const i = this.wingmen.indexOf(w);
    if (i >= 0) { this.wingmen.splice(i, 1); }
};

FPV.Swarm.prototype.wreck = function (s, id) {
    const w = this.add(s, 'wreck', id);
    w.age = 0;
    return w;
};

// Circle `point` (e.g. where the player just crashed).
FPV.Swarm.prototype.focus = function (point) {
    this.mode = 'support';
    this.center = { x: point.x, y: point.y, z: point.z };
    this.supportSince = this.time;
    this.wingmen.forEach(function (w) { if (w.role === 'join') { w.role = 'orbit'; } });
};

FPV.Swarm.prototype.predictImpact = function (L, env) {
    const ground = env.floorAt({ x: L.pos.x, y: L.pos.y, z: L.pos.z }).y;
    const t = FPV.clamp((L.pos.y - ground) / Math.max(-L.vel.y, 1), 0, 6);
    const p = FPV.add(L.pos, FPV.scale(L.vel, t));
    p.y = Math.max(env.floorAt({ x: p.x, y: L.pos.y, z: p.z }).y, ground - 50);
    return p;
};

FPV.Swarm.prototype.updateMode = function (dt, leader, env) {
    if (!leader || leader.crashed) { return; }
    const sp = FPV.len(leader.vel);
    const diving = sp > 8 && leader.vel.y / sp < -0.35;
    this.diveTime = diving ? this.diveTime + dt : 0;

    if (this.mode === 'formation' && this.diveTime > 0.3) {
        this.focus(this.predictImpact(leader, env));
    } else if (this.mode === 'support') {
        if (diving) {
            const p = this.predictImpact(leader, env);
            this.center = FPV.lerp3(this.center, p, 1 - Math.exp(-dt * 3));
        }
        const climbedOut = !diving && leader.vel.y > 2 &&
            leader.pos.y > this.center.y + this.opts.orbitMinHeight * 0.8;
        const farAway = FPV.len(FPV.horiz(FPV.sub(leader.pos, this.center))) > this.opts.orbitRadius * 4;
        if (this.time - this.supportSince > 3 && (climbedOut || farAway)) {
            this.mode = 'formation';
            this.center = null;
            this.wingmen.forEach(function (w) { if (w.role === 'orbit') { w.role = 'join'; } });
        }
    }
};

FPV.Swarm.prototype.groundBelow = function (env, p) {
    return env.floorAt({ x: p.x, y: p.y + 50, z: p.z }).y;
};

FPV.Swarm.prototype.formationCmd = function (w, idx, n, leader, env) {
    const o = this.opts;
    const L = leader;
    const hv = FPV.horiz(L.vel);
    const sp = FPV.len(hv);
    let dir = sp > 1 ? FPV.norm(hv) : FPV.norm(FPV.horiz(FPV.qRotate(L.q, { x: 0, y: 0, z: -1 })));
    if (FPV.len(dir) < 0.5) { dir = { x: 0, y: 0, z: -1 }; }
    const right = { x: -dir.z, y: 0, z: dir.x };
    const k = FPV.clamp((sp - 2) / 4, 0, 1);
    const blend = k * k * (3 - 2 * k);
    const t = this.time;

    const rank = Math.floor(idx / 2) + 1;
    const side = idx % 2 ? 1 : -1;
    const spacing = 5 + sp * 0.3;
    const wedge = FPV.add(FPV.add(FPV.scale(right, side * rank * spacing * 0.9), FPV.scale(dir, -rank * spacing * 0.7)),
        { x: 0, y: 1.5 + rank * 0.7, z: 0 });
    const ang = 2 * Math.PI * idx / Math.max(n, 1) + t * 0.15;
    const rad = 7 + n * 0.8;
    const ring = { x: Math.cos(ang) * rad, y: 3 + 0.5 * Math.sin(t * 0.8 + w.phase), z: Math.sin(ang) * rad };
    const wobble = { x: Math.sin(t * 0.7 + w.phase) * 0.6, y: Math.sin(t * 1.1 + w.phase) * 0.4, z: Math.cos(t * 0.9 + w.phase) * 0.6 };

    const slot = FPV.add(FPV.add(L.pos, FPV.lerp3(ring, wedge, blend)), wobble);
    slot.y = Math.max(slot.y, this.groundBelow(env, slot) + o.formationMinHeight);

    const toSlot = FPV.sub(slot, w.s.pos);
    const dist = FPV.len(toSlot);
    const vel = FPV.clampLen(FPV.add(L.vel, FPV.clampLen(FPV.scale(toSlot, 1.2), o.cruiseSpeed)), o.cruiseSpeed + sp);
    let face;
    if (dist > 25) { face = toSlot; }
    else if (blend > 0.5) { face = dir; }
    else { face = FPV.horiz(FPV.sub(slot, L.pos)); }
    return { vel: vel, face: face, maxTiltDeg: dist > 25 ? 65 : 50 };
};

FPV.Swarm.prototype.orbitCmd = function (w, idx, n, env) {
    const o = this.opts;
    const c = this.center;
    const t = this.time;
    const R = o.orbitRadius + 4 * Math.sin(t * 0.3 + w.phase);
    const omega = o.orbitSpeed / o.orbitRadius;
    const th = t * omega + 2 * Math.PI * idx / Math.max(n, 1);
    const groundC = Math.max(c.y, this.groundBelow(env, c));
    const slot = {
        x: c.x + Math.cos(th) * R,
        y: groundC + o.orbitMinHeight + 3 * Math.sin(t * 0.5 + w.phase),
        z: c.z + Math.sin(th) * R
    };
    slot.y = Math.max(slot.y, this.groundBelow(env, slot) + o.formationMinHeight);
    const tangent = { x: -Math.sin(th) * R * omega, y: 0, z: Math.cos(th) * R * omega };
    const vel = FPV.add(tangent, FPV.clampLen(FPV.scale(FPV.sub(slot, w.s.pos), 1.0), 30));
    return { vel: FPV.clampLen(vel, o.cruiseSpeed), face: FPV.horiz(FPV.sub(c, w.s.pos)), maxTiltDeg: 55 };
};

FPV.Swarm.prototype.attackCmd = function (w) {
    const T = w.target;
    const d = FPV.sub(T.pos, w.s.pos);
    const dist = FPV.len(d);
    const closing = Math.max(FPV.len(w.s.vel), 10);
    const tgo = Math.min(dist / closing, 3);
    const aim = FPV.add(T.pos, FPV.scale(T.vel || { x: 0, y: 0, z: 0 }, tgo));
    const dir = FPV.norm(FPV.sub(aim, w.s.pos));
    return { vel: FPV.scale(dir, this.opts.attackSpeed), face: dir, velGain: 3.5, maxTiltDeg: 80, maxAccel: 40 };
};

// Send every flying wingman (or `count` of them) at targets near the leader.
// targets: [{key, pos, vel}] - returns how many wingmen were tasked.
FPV.Swarm.prototype.attack = function (targets, leaderPos) {
    const o = this.opts;
    const inRange = targets.filter(function (t) { return FPV.dist(t.pos, leaderPos) <= o.attackRadius; });
    if (!inRange.length) { return 0; }
    const free = this.wingmen.filter(function (w) { return w.role === 'join' || w.role === 'orbit'; });
    let n = 0;
    free.forEach(function (w, i) {
        // Nearest targets first, spread round-robin across wingmen.
        const sorted = inRange.slice().sort(function (a, b) { return FPV.dist(a.pos, w.s.pos) - FPV.dist(b.pos, w.s.pos); });
        w.target = sorted[i % sorted.length];
        w.role = 'attack';
        n++;
    });
    return n;
};

FPV.Swarm.prototype.recall = function () {
    this.wingmen.forEach(function (w) { if (w.role === 'attack') { w.role = 'join'; w.target = null; } });
};

// Best airborne wingman to take over, judged by how close its camera already
// is to looking at `point`. Returns null if none qualifies.
FPV.Swarm.prototype.pickHandover = function (point) {
    let best = null;
    let bestScore = Infinity;
    const tune = this.tune;
    this.wingmen.forEach(function (w) {
        if (w.role === 'wreck' || w.role === 'attack' || w.s.crashed || w.s.onGround) { return; }
        const d = FPV.sub(point, w.s.pos);
        const dist = FPV.len(d);
        if (dist < 6 || dist > 600) { return; }
        const camF = FPV.qRotate(FPV.cameraPose(w.s, tune).q, { x: 0, y: 0, z: -1 });
        const ang = Math.acos(FPV.clamp(FPV.dot(FPV.norm(d), camF), -1, 1));
        const hd = FPV.norm(FPV.horiz(d)), hc = FPV.norm(FPV.horiz(camF));
        const yawAng = Math.acos(FPV.clamp(FPV.dot(hd, hc), -1, 1));
        const above = w.s.pos.y - point.y > 3 ? 0 : 1.5;
        const score = yawAng + ang * 0.5 + Math.abs(dist - 45) / 150 + above;
        if (score < bestScore) { bestScore = score; best = w; }
    });
    return best;
};

FPV.Swarm.prototype.aimError = function (w) {
    const camF = FPV.qRotate(FPV.cameraPose(w.s, this.tune).q, { x: 0, y: 0, z: -1 });
    return Math.acos(FPV.clamp(FPV.dot(FPV.norm(FPV.sub(w.aimPoint, w.s.pos)), camF), -1, 1));
};

function segPointDist(a, b, p) {
    const ab = FPV.sub(b, a);
    const l2 = FPV.dot(ab, ab);
    const t = l2 > 1e-9 ? FPV.clamp(FPV.dot(FPV.sub(p, a), ab) / l2, 0, 1) : 0;
    return FPV.dist(FPV.add(a, FPV.scale(ab, t)), p);
}

// Advance all wingmen. leader: controlled drone state (or null).
// targets: {key: {key,pos,vel}} currently known targets.
FPV.Swarm.prototype.update = function (dt, leader, env, targets) {
    const self = this;
    const o = this.opts;
    this.time += dt;
    this.updateMode(dt, leader, env);

    // Re-target or stand down attackers whose target vanished.
    this.wingmen.forEach(function (w) {
        if (w.role !== 'attack') { return; }
        const t = targets && targets[w.target.key];
        if (t) { w.target = t; } else { w.role = self.mode === 'support' ? 'orbit' : 'join'; w.target = null; }
    });

    const members = this.wingmen.filter(function (w) { return w.role === 'join' || w.role === 'orbit'; });
    const nullInput = { mode: 'direct', wDes: { x: 0, y: 0, z: 0 }, thrustCmd: 0 };

    const prev = {};
    this.wingmen.forEach(function (w) {
        prev[w.id] = { x: w.s.pos.x, y: w.s.pos.y, z: w.s.pos.z };
        w.cmd = null;
        if (w.role === 'wreck' || w.s.crashed) { return; }
        const idx = members.indexOf(w);
        if (w.role === 'attack') { w.cmd = self.attackCmd(w); }
        else if (w.role === 'aim') { w.cmd = { aimCamera: true, face: FPV.sub(w.aimPoint, w.s.pos), aimThrust: 0.22 }; }
        else if (self.mode === 'support' && self.center) { w.role = 'orbit'; w.cmd = self.orbitCmd(w, idx, members.length, env); }
        else if (leader) { w.role = 'join'; w.cmd = self.formationCmd(w, idx, members.length, leader, env); }
        else { w.cmd = { vel: { x: 0, y: 0, z: 0 }, face: null }; }
    });

    this.acc += dt;
    while (this.acc >= FPV.SWARM_STEP) {
        this.acc -= FPV.SWARM_STEP;
        this.wingmen.forEach(function (w) {
            const input = w.cmd && !w.s.crashed ? FPV.autopilot(w.s, w.cmd, self.tune) : nullInput;
            FPV.step(w.s, input, env, self.tune, FPV.SWARM_STEP);
        });
    }

    const keep = [];
    this.wingmen.forEach(function (w) {
        w.age += dt;
        if (w.role === 'attack' && !w.s.crashed &&
            segPointDist(prev[w.id], w.s.pos, w.target.pos) <= o.hitRadius) {
            const speed = FPV.len(w.s.vel);
            FPV.crash(w.s, 'IMPACT');
            w.hit = true;
            self.events.push({ type: 'impact', id: w.id, pos: w.target.pos, speed: speed, target: w.target.key });
        }
        while (w.s.events.length) {
            const ev = w.s.events.shift();
            if (ev.type !== 'crash' || w.role === 'wreck') { continue; }
            if (!w.hit) {
                self.events.push({ type: 'lost', id: w.id, reason: ev.reason, pos: w.s.pos });
                if (ev.speed >= o.impactMinSpeed && ev.reason !== 'WATER' && ev.reason !== 'HIT') {
                    self.events.push({ type: 'impact', id: w.id, pos: w.s.pos, speed: ev.speed, target: null });
                }
            }
            w.role = 'wreck';
            w.age = 0;
            w.target = null;
        }
        if (!(w.role === 'wreck' && w.age > o.wreckSeconds)) { keep.push(w); }
    });
    this.wingmen = keep;
};

// ===== remote.js =====
// ---------------------------------------------------------------------------
// remote.js - other players' drones (snapshot buffer + interpolation) and the
// renderer used for every drone that is not the one we are looking through.
// ---------------------------------------------------------------------------

FPV.INTERP_DELAY_MS = 120;
FPV.REMOTE_TIMEOUT_MS = 4000;

FPV.FLAG_ARMED = 1;
FPV.FLAG_CONTROLLED = 2;
FPV.FLAG_CRASHED = 4;

FPV.Remotes = function () {
    this.list = {};    // "pilotId:droneId" -> remote drone
    this.pilots = {};  // pilotId -> name (pilots currently flying)
};

FPV.Remotes.prototype.addPilot = function (pilotId, name) { this.pilots[pilotId] = name; };

FPV.Remotes.prototype.removePilot = function (pilotId) {
    delete this.pilots[pilotId];
    const prefix = pilotId + ':';
    for (const k in this.list) { if (k.indexOf(prefix) === 0) { delete this.list[k]; } }
};

FPV.Remotes.prototype.clear = function () { this.list = {}; this.pilots = {}; };

// entries: [[droneId, x, y, z, qx, qy, qz, qw, flags], ...] for one pilot.
FPV.Remotes.prototype.pushSwarm = function (pilotId, now, entries) {
    const seen = {};
    for (let i = 0; i < entries.length; i++) {
        const e = entries[i];
        const key = pilotId + ':' + e[0];
        seen[key] = true;
        let r = this.list[key];
        if (!r) { r = this.list[key] = { key: key, pilot: pilotId, id: e[0], snaps: [], last: 0, pose: null, flags: 0 }; }
        r.snaps.push({ t: now, pos: { x: e[1], y: e[2], z: e[3] }, q: FPV.qNorm({ x: e[4], y: e[5], z: e[6], w: e[7] }) });
        if (r.snaps.length > 20) { r.snaps.shift(); }
        r.last = now;
        r.flags = e[8];
    }
    const prefix = pilotId + ':';
    for (const k in this.list) {
        if (k.indexOf(prefix) === 0 && !seen[k]) { delete this.list[k]; }
    }
};

// Interpolate every remote to (now - delay). Drops remotes that went quiet.
FPV.Remotes.prototype.update = function (now) {
    const t = now - FPV.INTERP_DELAY_MS;
    for (const id in this.list) {
        const r = this.list[id];
        if (now - r.last > FPV.REMOTE_TIMEOUT_MS) { delete this.list[id]; continue; }
        const s = r.snaps;
        if (s.length === 0) { r.pose = null; continue; }
        if (s.length === 1 || t <= s[0].t) { r.pose = { pos: s[0].pos, q: s[0].q }; continue; }
        let i = 1;
        while (i < s.length && s[i].t < t) { i++; }
        if (i >= s.length) {
            // Ran out of data: extrapolate briefly from the last two snapshots.
            const a = s[s.length - 2], b = s[s.length - 1];
            const span = Math.max(b.t - a.t, 1);
            const k = Math.min((t - b.t) / span, 2);
            r.pose = { pos: FPV.lerp3(b.pos, FPV.add(b.pos, FPV.sub(b.pos, a.pos)), k), q: b.q };
        } else {
            const a = s[i - 1], b = s[i];
            const k = FPV.clamp((t - a.t) / Math.max(b.t - a.t, 1), 0, 1);
            r.pose = { pos: FPV.lerp3(a.pos, b.pos, k), q: FPV.qSlerp(a.q, b.q, k) };
        }
        // Velocity estimate for targeting.
        if (s.length >= 2) {
            const a = s[s.length - 2], b = s[s.length - 1];
            r.vel = FPV.scale(FPV.sub(b.pos, a.pos), 1000 / Math.max(b.t - a.t, 1));
        }
    }
};

// ---- drawing (game API) ----------------------------------------------------

FPV.RemoteRenderer = function () {
    this.ready = false;
    this.size = 0.5;          // drawn a bit larger than a real 5" quad so it is visible
    this.nameColor = new RGBA(255, 255, 255, 230);
    this.shadow = new RGBA(0, 0, 0, 200);
    this.armedColor = new RGBA(80, 255, 120, 230);
    this.maxText = new Vector2f(1000, 100);
    this.xAxis = new Vector3f(1, 0, 0);
    try {
        this.texTop = new Texture('package://fpvdrone/textures/drone_top.png');
        this.texSide = new Texture('package://fpvdrone/textures/drone_side.png');
        this.texBoom = new Texture('package://fpvdrone/textures/explosion.png');
        this.ready = true;
    } catch (e) {
        if (typeof jcmp.print === 'function') { jcmp.print('[fpvdrone] could not load textures: ' + e); }
    }
};

// 3D pass (GameUpdateRender): textured quads at each pose [{pos, q}].
FPV.RemoteRenderer.prototype.draw3d = function (r, poses, camPos, modelRotSign) {
    if (!this.ready) { return; }
    const half = this.size / 2;
    const topPos = new Vector3f(-half, -half, 0);
    const topSize = new Vector2f(this.size, this.size);
    const sideH = this.size * 0.25;
    const sidePos = new Vector3f(-half, -sideH / 2, 0);
    const sideSize = new Vector2f(this.size, sideH);
    for (let i = 0; i < poses.length; i++) {
        const p = poses[i];
        if (FPV.dist(p.pos, camPos) > 1500 || FPV.dist(p.pos, camPos) < 0.3) { continue; }
        const aa = FPV.qToAxisAngle(p.q);
        const pos = new Vector3f(p.pos.x, p.pos.y, p.pos.z);
        const axis = new Vector3f(aa.axis.x, aa.axis.y, aa.axis.z);
        const angle = aa.angle * modelRotSign;
        // Matrices are rebuilt rather than reused in case Matrix ops mutate.
        // Top-down silhouette lying in the body XZ plane...
        r.SetTransform(new Matrix().Translate(pos).Rotate(angle, axis).Rotate(Math.PI / 2, this.xAxis));
        r.DrawTexture(this.texTop, topPos, topSize);
        // ...plus a vertical strip across the body so it is visible edge-on.
        r.SetTransform(new Matrix().Translate(pos).Rotate(angle, axis));
        r.DrawTexture(this.texSide, sidePos, sideSize);
    }
};

// 2D pass (Render): labels [{pos, text, color, size}] and impact flashes.
FPV.RemoteRenderer.prototype.draw2d = function (r, labels, effects, camPos, now) {
    for (let i = 0; i < labels.length; i++) {
        const l = labels[i];
        const d = FPV.dist(l.pos, camPos);
        if (d > 1500 || d < 0.5) { continue; }
        const sp = r.WorldToScreen(new Vector3f(l.pos.x, l.pos.y + 0.6, l.pos.z));
        if (!sp || (sp.x === -1 && sp.y === -1)) { continue; }
        const text = l.text + '  ' + Math.round(d) + 'm';
        const size = l.size || (d < 50 ? 22 : 18);
        const m = r.MeasureText(text, size, 'Arial');
        const x = sp.x - m.x / 2, y = sp.y - m.y;
        r.DrawText(text, new Vector3f(x + 1, y + 1, 0.5), this.maxText, this.shadow, size, 'Arial');
        r.DrawText(text, new Vector3f(x, y, 0.5), this.maxText, l.color || this.nameColor, size, 'Arial');
    }
    if (!this.ready) { return; }
    for (let i = 0; i < effects.length; i++) {
        const e = effects[i];
        const age = (now - e.t0) / 1000;
        if (age < 0 || age > 0.7) { continue; }
        const d = Math.max(FPV.dist(e.pos, camPos), 1);
        const sp = r.WorldToScreen(new Vector3f(e.pos.x, e.pos.y, e.pos.z));
        if (!sp || (sp.x === -1 && sp.y === -1)) { continue; }
        const s = FPV.clamp(2400 / d, 24, 900) * (0.4 + age * 1.6);
        r.DrawTexture(this.texBoom, new Vector2f(sp.x - s / 2, sp.y - s / 2), new Vector2f(s, s));
    }
};

// ===== client.js =====
// ---------------------------------------------------------------------------
// client.js - glue between the simulation and JC3MP: camera, input from the
// UI, the swarm, networking, remote drones and the OSD feed.
// ---------------------------------------------------------------------------

const STEP = 1 / 240;           // physics substep
const OSD_INTERVAL_MS = 33;
const HANDOVER_MAX_MS = 900;    // longest the auto-aim may take before control passes
const MODES = ['acro', 'angle', 'horizon'];
const VIEWS = ['fpv', 'chase', 'los'];

// Server-provided config (see packages/fpvdrone/config.js). Defaults here are
// used until the server answers.
const cfg = {
    enabled: true,
    seaLevel: 1024,
    syncRateHz: 20,
    followDistance: 250,
    followDepth: 40,
    videoRange: 2500,
    maxAltitude: 4500,
    tuneOverrides: {},
    swarm: { enabled: true },
    damage: { enabled: true, minSpeed: 10 }
};

// Local pilot settings (edited in the F8 panel, persisted by the UI).
const settings = {
    tune: FPV.cloneTune(FPV.DEFAULT_TUNE),
    camera: { eulerOrder: 'YXZ', pitchSign: -1, yawSign: -1, rollSign: -1, fovDeg: 92, modelRotSign: 1 },
    mode: 'acro',
    altHold: false,
    view: 'fpv'
};

let tune = FPV.cloneTune(FPV.DEFAULT_TUNE);

let status = 'idle';            // idle | pending | flying
let pendingSince = 0;
let drone = null;               // the drone the player is flying
let droneId = 0;                // its id within our swarm (ids are sent over the network)
let launch = null;              // {x,y,z} where the pilot is standing
let lastFollow = null;
let lastFrame = 0;
let acc = 0;
let lastSend = 0;
let lastOsd = 0;
let lastFollowCheck = 0;
let lastControlsAssert = 0;
let savedFov = null;
let chatOpen = false;
let menuOpen = false;
let prevCam = null;             // camera pose we set last frame (for lookAt validation)
let chaseYaw = 0;
let videoGlitchUntil = 0;
let armSwitchPrev = null;
let armBlockedReason = '';
let handover = null;            // {w, t0, point} while a wingman auto-aims before we take it
let banner = null;              // {text, until} short OSD banner
const effects = [];             // impact flashes [{pos, t0}]
const targetTracks = {};        // key -> {pos, t} for velocity estimates

const input = { throttle: 0, roll: 0, pitch: 0, yaw: 0, mode: 'acro', altHold: false, source: 'keyboard' };

const world = new FPV.World(cfg.seaLevel);
const remotes = new FPV.Remotes();
const renderer = new FPV.RemoteRenderer();
let swarm = new FPV.Swarm({}, tune);

const ui = new WebUIWindow('fpvdrone', 'package://fpvdrone/ui/index.html',
    new Vector2(jcmp.viewportSize.x, jcmp.viewportSize.y));
ui.autoResize = true;

const COLOR_WING = new RGBA(90, 220, 255, 230);
const COLOR_ATTACK = new RGBA(255, 90, 70, 240);
const COLOR_WRECK = new RGBA(150, 150, 150, 200);
const COLOR_ARMED = new RGBA(80, 255, 120, 230);
const COLOR_NAME = new RGBA(255, 255, 255, 230);

function log(msg) {
    if (typeof jcmp.print === 'function') { jcmp.print('[fpvdrone] ' + msg); }
}

function notify(text, kind) {
    jcmp.ui.CallEvent('fpv/notify', text, kind || 'info');
}

function showBanner(text, ms) {
    banner = { text: text, until: Date.now() + (ms || 1500) };
}

function toVec3f(v) { return new Vector3f(v.x, v.y, v.z); }
function fromVec3f(v) { return { x: v.x, y: v.y, z: v.z }; }

function rebuildTune() {
    tune = FPV.cloneTune(settings.tune);
    FPV.mergeTune(tune, cfg.tuneOverrides);
    swarm.setTune(tune);
    swarm.configure(cfg.swarm);
    swarm.opts.impactMinSpeed = cfg.damage.minSpeed;
}

function swarmEnabled() { return cfg.swarm.enabled !== false; }

// ---- start / stop ----------------------------------------------------------

function requestStart() {
    if (status !== 'idle') { return; }
    if (!cfg.enabled) { notify('FPV drones are disabled on this server', 'warn'); return; }
    status = 'pending';
    pendingSince = Date.now();
    jcmp.events.CallRemote('fpv/request_start');
}

function begin() {
    const lp = jcmp.localPlayer;
    launch = fromVec3f(lp.position);
    const heading = FPV.fromGameYaw(lp.camera.rotation.y, settings.camera);
    const fwd = FPV.qRotate(heading, { x: 0, y: 0, z: -1 });

    world.seaLevel = cfg.seaLevel;
    world.reset();
    world.addPad(launch.x, launch.y, launch.z, 6.0);

    swarm = new FPV.Swarm({}, tune);
    rebuildTune();
    const start = FPV.add(launch, { x: fwd.x * 1.5, y: tune.collisionRadius, z: fwd.z * 1.5 });
    drone = FPV.createState(start, heading);
    drone.onGround = true;
    droneId = 0;
    handover = null;

    savedFov = lp.camera.fieldOfView;
    lp.frozen = true;
    lp.controlsEnabled = false;
    lp.camera.attachedToPlayer = false;
    lp.camera.fieldOfView = settings.camera.fovDeg * FPV.DEG;
    if (typeof jcmp.ui.HideHud === 'function') { jcmp.ui.HideHud(); }

    lastFollow = { x: launch.x, y: launch.y, z: launch.z };
    lastFrame = Date.now();
    acc = 0;
    prevCam = null;
    chaseYaw = FPV.yawOf(heading);
    armSwitchPrev = null;
    armBlockedReason = '';
    status = 'flying';
    jcmp.ui.CallEvent('fpv/active', true);
    notify('Drone ready - arm to take off (E or your arm switch)', 'info');
}

function end(tellServer) {
    if (status === 'pending') { status = 'idle'; return; }
    if (status !== 'flying') { return; }
    status = 'idle';
    const lp = jcmp.localPlayer;
    lp.camera.attachedToPlayer = true;
    if (savedFov !== null) { lp.camera.fieldOfView = savedFov; }
    lp.frozen = false;
    lp.controlsEnabled = !chatOpen && !menuOpen;
    if (typeof jcmp.ui.ShowHud === 'function') { jcmp.ui.ShowHud(); }
    drone = null;
    handover = null;
    swarm = new FPV.Swarm({}, tune);
    jcmp.ui.CallEvent('fpv/active', false);
    if (tellServer) { jcmp.events.CallRemote('fpv/stop'); }
}

function resetDrone() {
    if (!drone || !launch) { return; }
    if (handover) { finishHandover(); }
    const heading = FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, FPV.yawOf(drone.q));
    const fwd = FPV.qRotate(heading, { x: 0, y: 0, z: -1 });
    drone = FPV.createState(FPV.add(launch, { x: fwd.x * 1.5, y: tune.collisionRadius, z: fwd.z * 1.5 }), heading);
    drone.onGround = true;
    armSwitchPrev = null;
    jcmp.events.CallRemote('fpv/follow', launch.x, launch.y, launch.z, 1);
    lastFollow = { x: launch.x, y: launch.y, z: launch.z };
    notify('Drone reset to launch point', 'info');
}

// ---- arming / commands -----------------------------------------------------

function armRequest(on) {
    if (!drone || handover) { return; }
    if (!on) { FPV.disarm(drone); return; }
    input.mode = settings.mode;
    input.altHold = settings.altHold;
    const reason = FPV.tryArm(drone, input);
    if (reason) {
        armBlockedReason = reason;
        notify(reason === 'THROTTLE' ? 'Arming blocked: lower the throttle' :
            reason === 'WATER' ? 'Drone is in the water - press R to reset' : 'Arming blocked: ' + reason, 'warn');
    } else {
        armBlockedReason = '';
    }
}

function command(name) {
    if (chatOpen) { return; }
    switch (name) {
        case 'toggle':
            if (status === 'flying') { end(true); } else { requestStart(); }
            break;
        case 'arm':
            if (drone) { armRequest(!drone.armed); }
            break;
        case 'reset':
            resetDrone();
            break;
        case 'mode':
            settings.mode = MODES[(MODES.indexOf(settings.mode) + 1) % MODES.length];
            jcmp.ui.CallEvent('fpv/mode_changed', settings.mode, settings.altHold);
            break;
        case 'althold':
            settings.altHold = !settings.altHold;
            jcmp.ui.CallEvent('fpv/mode_changed', settings.mode, settings.altHold);
            break;
        case 'view':
            settings.view = VIEWS[(VIEWS.indexOf(settings.view) + 1) % VIEWS.length];
            jcmp.ui.CallEvent('fpv/view_changed', settings.view);
            break;
        case 'call':
            callWingman();
            break;
        case 'attack':
            swarmAttack();
            break;
        case 'switch':
            switchDrone();
            break;
    }
}

// ---- swarm -----------------------------------------------------------------

// Launch a wingman. Near home it lifts off from the launch pad; far away it
// arrives from behind and above (as if dispatched from a nearby truck).
function callWingman() {
    if (!drone || status !== 'flying') { return; }
    if (!swarmEnabled()) { notify('Swarm is disabled on this server', 'warn'); return; }
    const n = swarm.flying().length;
    let pos;
    if (FPV.dist(launch, drone.pos) < 600) {
        const a = n * 1.3;
        pos = { x: launch.x + Math.cos(a) * 3, y: launch.y + tune.collisionRadius, z: launch.z + Math.sin(a) * 3 };
    } else {
        const back = FPV.qRotate(FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, FPV.yawOf(drone.q)), { x: 0, y: 0, z: 150 });
        pos = FPV.add(drone.pos, { x: back.x, y: 30, z: back.z });
    }
    const w = swarm.spawn(pos, FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, FPV.yawOf(drone.q)));
    if (!w) { notify('Swarm full (' + swarm.opts.maxWingmen + ' wingmen)', 'warn'); return; }
    if (pos.y > launch.y + 5) { w.s.onGround = false; }
    notify('Wingman W' + w.id + ' inbound', 'info');
}

function gatherTargets() {
    const now = Date.now();
    const out = {};
    function add(key, p) {
        const pos = { x: p.x, y: p.y, z: p.z };
        if (!FPV.isFiniteVec(pos)) { return; }
        const prev = targetTracks[key];
        let vel = { x: 0, y: 0, z: 0 };
        if (prev && now - prev.t > 0 && now - prev.t < 1000) {
            vel = FPV.scale(FPV.sub(pos, prev.pos), 1000 / (now - prev.t));
            if (FPV.len(vel) > 150) { vel = { x: 0, y: 0, z: 0 }; }
        }
        if (!prev || now - prev.t > 50) { targetTracks[key] = { pos: pos, t: now }; }
        out[key] = { key: key, pos: pos, vel: vel };
    }
    const me = jcmp.localPlayer.networkId;
    if (jcmp.players) {
        for (let i = 0; i < jcmp.players.length; i++) {
            const p = jcmp.players[i];
            if (!p || p.networkId === me || remotes.pilots[p.networkId] !== undefined) { continue; }
            if (typeof p.health === 'number' && p.health <= 0) { continue; }
            // Aim at the chest rather than the feet.
            const pp = p.position;
            if (pp) { add('p' + p.networkId, { x: pp.x, y: pp.y + 1.0, z: pp.z }); }
        }
    }
    if (jcmp.vehicles) {
        for (let i = 0; i < jcmp.vehicles.length; i++) {
            const v = jcmp.vehicles[i];
            if (v && v.position) { add('v' + (v.networkId !== undefined ? v.networkId : i), { x: v.position.x, y: v.position.y + 0.8, z: v.position.z }); }
        }
    }
    for (const k in remotes.list) {
        const r = remotes.list[k];
        if (r.pose && !(r.flags & FPV.FLAG_CRASHED)) { add('d' + k, r.pose.pos); }
    }
    return out;
}

function swarmAttack() {
    if (!drone || !swarmEnabled()) { return; }
    if (swarm.attackers().length) {
        swarm.recall();
        notify('Swarm attack called off', 'info');
        return;
    }
    if (!swarm.flying().length) { notify('No wingmen - call one first', 'warn'); return; }
    const targets = gatherTargets();
    const list = Object.keys(targets).map(function (k) { return targets[k]; });
    const n = swarm.attack(list, drone.pos);
    if (!n) { notify('No targets within ' + swarm.opts.attackRadius + 'm', 'warn'); return; }
    showBanner('SWARM ATTACK x' + n, 1500);
    notify(n + ' wingm' + (n === 1 ? 'an' : 'en') + ' attacking', 'warn');
}

// Hand control to wingman `w`. The old drone rejoins as a wingman if it can
// still fly, otherwise it is left as a wreck.
function takeControl(w) {
    swarm.remove(w);
    if (drone.crashed || drone.inWater) { swarm.wreck(drone, droneId); }
    else { swarm.add(drone, 'join', droneId); }
    drone = w.s;
    droneId = w.id;
    drone.events = [];
    drone.armed = true;
    drone.crashed = false;
    armBlockedReason = '';
    videoGlitchUntil = Date.now() + 350;
    lastFollow = { x: drone.pos.x - 1e6, y: 0, z: 0 };   // force a follow update
    showBanner('LINK > W' + w.id, 1200);
}

function switchDrone() {
    if (!drone || handover) { return; }
    const flying = swarm.wingmen.filter(function (w) { return w.role !== 'wreck' && w.role !== 'aim' && !w.s.crashed; })
        .sort(function (a, b) { return a.id - b.id; });
    if (!flying.length) { notify('No other drone to switch to', 'warn'); return; }
    const next = flying.find(function (w) { return w.id > droneId; }) || flying[0];
    takeControl(next);
}

// Our drone just crashed: circle the impact point and hand control to the
// wingman best placed to see it, after it has pointed its camera there.
function startHandover(point) {
    if (!swarmEnabled()) { return; }
    swarm.focus(point);
    const w = swarm.pickHandover(point);
    if (!w) { return; }
    w.role = 'aim';
    w.aimPoint = { x: point.x, y: point.y, z: point.z };
    handover = { w: w, t0: Date.now(), point: w.aimPoint };
    showBanner('LINK > W' + w.id + '  AUTO-AIM', HANDOVER_MAX_MS + 600);
}

function finishHandover() {
    const h = handover;
    handover = null;
    if (!h || h.w.s.crashed || swarm.wingmen.indexOf(h.w) < 0) { return; }
    takeControl(h.w);
}

function sendImpact(id, pos, speed) {
    if (!cfg.damage.enabled || speed < cfg.damage.minSpeed) { return; }
    jcmp.events.CallRemote('fpv/impact', id, pos.x, pos.y, pos.z, speed);
}

// ---- camera ----------------------------------------------------------------

function cameraFor(view, dt) {
    const s = handover ? handover.w.s : drone;
    if (view === 'chase') {
        const target = FPV.yawOf(s.q);
        chaseYaw += FPV.wrapAngle(target - chaseYaw) * (1 - Math.exp(-dt * 4));
        const h = FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, chaseYaw);
        const back = FPV.qRotate(h, { x: 0, y: 0, z: 3.0 });
        const pos = FPV.add(s.pos, { x: back.x, y: 1.0, z: back.z });
        return { pos: pos, q: FPV.lookRotation(FPV.sub(s.pos, pos)) };
    }
    if (view === 'los') {
        const eye = FPV.add(launch, { x: 0, y: 1.7, z: 0 });
        const d = FPV.sub(s.pos, eye);
        return { pos: eye, q: FPV.len(d) > 0.5 ? FPV.lookRotation(d) : FPV.qAxisAngle({ x: 0, y: 1, z: 0 }, FPV.yawOf(s.q)) };
    }
    return FPV.cameraPose(s, tune);
}

function applyCamera(cam) {
    const c = jcmp.localPlayer.camera;
    const e = FPV.toGameEuler(cam.q, settings.camera);
    c.position = toVec3f(cam.pos);
    c.rotation = new Vector3f(e.x, e.y, e.z);
}

// ---- per-frame -------------------------------------------------------------

function onOwnCrash(ev) {
    videoGlitchUntil = Date.now() + 600;
    jcmp.events.CallRemote('fpv/crash', ev.reason);
    if (ev.reason !== 'WATER' && ev.reason !== 'HIT') { sendImpact(droneId, drone.pos, ev.speed); }
    startHandover(drone.pos);
}

function probeTerrain(dt) {
    if (!prevCam) { return; }
    let hit = null;
    try { hit = jcmp.localPlayer.lookAt; } catch (e) { hit = null; }
    if (!hit) { return; }
    const camFwd = FPV.qRotate(prevCam.q, { x: 0, y: 0, z: -1 });
    const dist = world.probe(prevCam.pos, camFwd, fromVec3f(hit));
    if (dist < 0 || settings.view !== 'fpv' || drone.crashed || handover) { return; }

    // Head-on obstacle check along the camera ray.
    const along = FPV.dot(drone.vel, camFwd);
    const reach = tune.collisionRadius + 0.2 + Math.max(along, 0) * dt * 1.5;
    if (along > 1.5 && dist < reach) {
        const h = fromVec3f(hit);
        drone.pos = FPV.sub(h, FPV.scale(camFwd, tune.collisionRadius + 0.05));
        if (along > tune.crashSpeed) {
            // Report the crash at the surface we hit (the attack point).
            FPV.crash(drone, 'IMPACT');
            const ev = drone.events[drone.events.length - 1];
            ev.speed = along;
            drone.pos = h;
            drone.vel = FPV.scale(drone.vel, -0.1);
            // Looking down at what we hit -> it is ground, rest on it. A wall
            // hit lets the wreck drop to whatever floor is known below.
            if (camFwd.y < -0.5) { world.addPad(h.x, h.y, h.z, 1.5); }
        } else {
            // Gentle bump: bounce off, stay armed.
            drone.vel = FPV.sub(drone.vel, FPV.scale(camFwd, along * 1.4));
        }
    }
}

function packDrone(id, s, flags) {
    const r2 = function (v) { return Math.round(v * 100) / 100; };
    const r4 = function (v) { return Math.round(v * 10000) / 10000; };
    return [id, r2(s.pos.x), r2(s.pos.y), r2(s.pos.z), r4(s.q.x), r4(s.q.y), r4(s.q.z), r4(s.q.w), flags];
}

function sendState(now) {
    if (now - lastSend < 1000 / cfg.syncRateHz) { return; }
    lastSend = now;
    const list = [packDrone(droneId, drone, FPV.FLAG_CONTROLLED |
        (drone.armed ? FPV.FLAG_ARMED : 0) | (drone.crashed ? FPV.FLAG_CRASHED : 0))];
    swarm.wingmen.forEach(function (w) {
        list.push(packDrone(w.id, w.s, (w.s.armed ? FPV.FLAG_ARMED : 0) | (w.s.crashed ? FPV.FLAG_CRASHED : 0)));
    });
    jcmp.events.CallRemote('fpv/swarm', JSON.stringify(list));
}

function followCheck(now) {
    // The world streams around the (frozen) character, so drag it along
    // underneath the drone when we get far away.
    if (now - lastFollowCheck < 1000 || !cfg.followDistance) { return; }
    lastFollowCheck = now;
    const dx = drone.pos.x - lastFollow.x, dz = drone.pos.z - lastFollow.z;
    if (dx * dx + dz * dz > cfg.followDistance * cfg.followDistance) {
        jcmp.events.CallRemote('fpv/follow', drone.pos.x, drone.pos.y, drone.pos.z, 0);
        lastFollow = { x: drone.pos.x, y: drone.pos.y, z: drone.pos.z };
    }
}

function sendOsd(now) {
    if (now - lastOsd < OSD_INTERVAL_MS) { return; }
    lastOsd = now;
    const s = handover ? handover.w.s : drone;
    const fwd = FPV.qRotate(s.q, { x: 0, y: 0, z: -1 });
    const right = FPV.qRotate(s.q, { x: 1, y: 0, z: 0 });
    const toHome = FPV.sub(launch, s.pos);
    const distHome = Math.sqrt(toHome.x * toHome.x + toHome.z * toHome.z);
    const homeYaw = Math.atan2(-toHome.x, -toHome.z);
    const vr = cfg.videoRange;
    let noise = FPV.clamp((FPV.dist(launch, s.pos) - vr * 0.75) / (vr * 0.25), 0, 1);
    if (now < videoGlitchUntil) { noise = Math.max(noise, (videoGlitchUntil - now) / 600); }
    jcmp.ui.CallEvent('fpv/osd', JSON.stringify({
        armed: s.armed,
        crashed: s.crashed,
        reason: s.crashReason,
        blocked: armBlockedReason,
        mode: settings.mode,
        altHold: settings.altHold,
        view: settings.view,
        thr: input.throttle,
        motor: s.motor,
        speed: FPV.len(s.vel) * 3.6,
        vspeed: s.vel.y,
        alt: s.pos.y - launch.y,
        asl: s.pos.y - cfg.seaLevel,
        home: distHome,
        homeDir: FPV.wrapAngle(homeYaw - FPV.yawOf(s.q)),
        pitch: Math.asin(FPV.clamp(fwd.y, -1, 1)),
        roll: Math.asin(FPV.clamp(-right.y, -1, 1)),
        tilt: tune.cameraTiltDeg,
        cell: drone.cellVoltage,
        cells: tune.battery.cells,
        mah: drone.usedMah,
        cap: tune.battery.capacityMah,
        batt: tune.battery.enabled && !handover,
        amps: drone.currentA,
        time: drone.flightTime,
        noise: noise,
        probe: world.probeValid,
        src: input.source,
        swarm: swarmEnabled() ? {
            n: swarm.flying().length,
            max: swarm.opts.maxWingmen,
            mode: swarm.mode,
            atk: swarm.attackers().length,
            id: droneId
        } : null,
        handover: !!handover,
        banner: banner && now < banner.until ? banner.text : ''
    }));
}

function ownPoses() {
    const poses = [];
    const viewing = handover ? handover.w.s : drone;
    if (drone && (settings.view !== 'fpv' || viewing !== drone)) { poses.push({ pos: drone.pos, q: drone.q }); }
    swarm.wingmen.forEach(function (w) {
        if (settings.view === 'fpv' && w.s === viewing) { return; }
        poses.push({ pos: w.s.pos, q: w.s.q });
    });
    return poses;
}

function frame(r) {
    const now = Date.now();

    if (status === 'pending' && now - pendingSince > 4000) {
        status = 'idle';
        notify('Server did not answer the FPV request', 'warn');
    }

    remotes.update(now);
    const camPos = fromVec3f(jcmp.localPlayer.camera.position);
    const poses = [];
    for (const k in remotes.list) { if (remotes.list[k].pose) { poses.push(remotes.list[k].pose); } }
    if (status === 'flying' && drone) { Array.prototype.push.apply(poses, ownPoses()); }
    renderer.draw3d(r, poses, camPos, settings.camera.modelRotSign);

    if (status !== 'flying' || !drone) { return; }

    let dt = (now - lastFrame) / 1000;
    lastFrame = now;
    if (!(dt > 0)) { dt = 0; }
    if (dt > 0.1) { dt = 0.1; }   // hitch / alt-tab: don't explode

    input.mode = settings.mode;
    input.altHold = settings.altHold;

    acc += dt;
    while (acc >= STEP) {
        FPV.step(drone, input, world, tune, STEP);
        acc -= STEP;
    }
    if (drone.pos.y > cfg.maxAltitude) { drone.pos.y = cfg.maxAltitude; if (drone.vel.y > 0) { drone.vel.y = 0; } }

    probeTerrain(dt);

    while (drone.events.length) {
        const ev = drone.events.shift();
        if (ev.type === 'crash') { onOwnCrash(ev); }
    }

    // Wingmen.
    if (swarm.wingmen.length) {
        const targets = swarm.attackers().length ? gatherTargets() : {};
        swarm.update(dt, drone, world, targets);
        while (swarm.events.length) {
            const ev = swarm.events.shift();
            if (ev.type === 'impact') { sendImpact(ev.id, ev.pos, ev.speed); }
            else if (ev.type === 'lost') { notify('Wingman W' + ev.id + (ev.reason === 'WATER' ? ' ditched' : ' lost'), 'warn'); }
        }
    }
    if (handover) {
        if (handover.w.s.crashed || swarm.wingmen.indexOf(handover.w) < 0) {
            handover = null;
        } else if (swarm.aimError(handover.w) < 6 * FPV.DEG || now - handover.t0 > HANDOVER_MAX_MS) {
            finishHandover();
        }
    }

    const cam = cameraFor(settings.view, dt);
    applyCamera(cam);
    prevCam = cam;

    if (now - lastControlsAssert > 500) {
        lastControlsAssert = now;
        jcmp.localPlayer.controlsEnabled = false;
    }

    sendState(now);
    followCheck(now);
    sendOsd(now);
}

function labels() {
    const out = [];
    for (const k in remotes.list) {
        const r = remotes.list[k];
        if (!r.pose || !(r.flags & FPV.FLAG_CONTROLLED)) { continue; }
        out.push({ pos: r.pose.pos, text: remotes.pilots[r.pilot] || ('Pilot ' + r.pilot),
            color: (r.flags & FPV.FLAG_ARMED) ? COLOR_ARMED : COLOR_NAME });
    }
    if (status === 'flying' && drone) {
        swarm.wingmen.forEach(function (w) {
            if (handover && w === handover.w) { return; }
            const tag = w.role === 'attack' ? 'W' + w.id + ' ATK' : (w.role === 'wreck' ? 'W' + w.id + ' X' : 'W' + w.id);
            out.push({ pos: w.s.pos, text: tag, size: 14,
                color: w.role === 'attack' ? COLOR_ATTACK : (w.role === 'wreck' ? COLOR_WRECK : COLOR_WING) });
        });
    }
    return out;
}

// ---- events: game ----------------------------------------------------------

jcmp.events.Add('GameUpdateRender', (r) => {
    try { frame(r); } catch (e) { log('frame error: ' + (e && e.stack ? e.stack : e)); }
});

jcmp.events.Add('Render', (r) => {
    try {
        const now = Date.now();
        while (effects.length && now - effects[0].t0 > 1000) { effects.shift(); }
        renderer.draw2d(r, labels(), effects, fromVec3f(jcmp.localPlayer.camera.position), now);
    } catch (e) { log('render error: ' + e); }
});

// ---- events: UI ------------------------------------------------------------

jcmp.ui.AddEvent('fpv/ui/ready', () => {
    jcmp.events.CallRemote('fpv/ready');
});

jcmp.ui.AddEvent('fpv/ui/cmd', (name) => { command(name); });

jcmp.ui.AddEvent('fpv/ui/menu', (open) => {
    menuOpen = !!open;
    if (status !== 'flying') { jcmp.localPlayer.controlsEnabled = !menuOpen && !chatOpen; }
});

// Sticks arrive already mapped/calibrated by the UI (gamepad or keyboard).
// arm/mode are -2 when the pilot has not mapped a switch.
jcmp.ui.AddEvent('fpv/ui/sticks', (t, roll, pitch, yaw, arm, mode, source) => {
    input.throttle = FPV.clamp(+t || 0, 0, 1);
    input.roll = FPV.clamp(+roll || 0, -1, 1);
    input.pitch = FPV.clamp(+pitch || 0, -1, 1);
    input.yaw = FPV.clamp(+yaw || 0, -1, 1);
    input.source = source;
    if (!drone || chatOpen) { return; }

    if (arm > -1.5) {
        const on = arm > 0.5;
        if (armSwitchPrev !== null && on !== armSwitchPrev) { armRequest(on); }
        armSwitchPrev = on;
        if (!on && drone.armed && !handover) { FPV.disarm(drone); }
    }
    if (mode > -1.5) {
        const m = mode < -0.33 ? 'acro' : (mode > 0.33 ? 'angle' : 'horizon');
        if (m !== settings.mode) {
            settings.mode = m;
            jcmp.ui.CallEvent('fpv/mode_changed', settings.mode, settings.altHold);
        }
    }
});

jcmp.ui.AddEvent('fpv/ui/settings', (json) => {
    let s;
    try { s = JSON.parse(json); } catch (e) { return; }
    if (!s || typeof s !== 'object') { return; }
    if (s.tune) { FPV.mergeTune(settings.tune, s.tune); }
    if (s.camera) {
        const c = settings.camera;
        if (['XYZ', 'YXZ', 'ZXY', 'ZYX', 'YZX', 'XZY'].indexOf(s.camera.eulerOrder) >= 0) { c.eulerOrder = s.camera.eulerOrder; }
        ['pitchSign', 'yawSign', 'rollSign', 'modelRotSign'].forEach((k) => {
            if (s.camera[k] === 1 || s.camera[k] === -1) { c[k] = s.camera[k]; }
        });
        if (isFinite(s.camera.fovDeg)) { c.fovDeg = FPV.clamp(+s.camera.fovDeg, 40, 150); }
    }
    if (MODES.indexOf(s.mode) >= 0) { settings.mode = s.mode; }
    if (typeof s.altHold === 'boolean') { settings.altHold = s.altHold; }
    if (VIEWS.indexOf(s.view) >= 0) { settings.view = s.view; }
    rebuildTune();
    if (status === 'flying') { jcmp.localPlayer.camera.fieldOfView = settings.camera.fovDeg * FPV.DEG; }
});

// Other packages' chat (chat / chat2) broadcast this while the input box is open.
jcmp.ui.AddEvent('chat_input_state', (s) => {
    chatOpen = !!s;
    jcmp.ui.CallEvent('fpv/chat', chatOpen);
});

// ---- events: server --------------------------------------------------------

jcmp.events.AddRemoteCallable('fpv/config', (json) => {
    try {
        const c = JSON.parse(json);
        for (const k in cfg) {
            if (Object.prototype.hasOwnProperty.call(c, k) && typeof c[k] === typeof cfg[k] && c[k] !== null) { cfg[k] = c[k]; }
        }
        world.seaLevel = cfg.seaLevel;
        rebuildTune();
        jcmp.ui.CallEvent('fpv/config', JSON.stringify(cfg));
    } catch (e) { log('bad config: ' + e); }
});

jcmp.events.AddRemoteCallable('fpv/toggle', () => {
    if (status === 'flying') { end(true); } else { requestStart(); }
});

jcmp.events.AddRemoteCallable('fpv/start', () => {
    if (status === 'pending') { begin(); }
});

jcmp.events.AddRemoteCallable('fpv/denied', (reason) => {
    if (status === 'pending') { status = 'idle'; }
    notify(reason, 'warn');
});

jcmp.events.AddRemoteCallable('fpv/force_stop', (reason) => {
    end(false);
    if (reason) { notify(reason, 'warn'); }
});

jcmp.events.AddRemoteCallable('fpv/remote_start', (id, name) => {
    if (id === jcmp.localPlayer.networkId) { return; }
    remotes.addPilot(id, name);
});

jcmp.events.AddRemoteCallable('fpv/remote_stop', (id) => { remotes.removePilot(id); });

jcmp.events.AddRemoteCallable('fpv/remote_swarm', (id, json) => {
    if (id === jcmp.localPlayer.networkId) { return; }
    let list;
    try { list = JSON.parse(json); } catch (e) { return; }
    if (Array.isArray(list)) { remotes.pushSwarm(id, Date.now(), list); }
});

jcmp.events.AddRemoteCallable('fpv/remote_crash', (name, reason) => {
    jcmp.ui.CallEvent('fpv/feed', name + (reason === 'WATER' ? ' ditched in the sea' : ' crashed'));
});

jcmp.events.AddRemoteCallable('fpv/remote_impact', (x, y, z) => {
    effects.push({ pos: { x: x, y: y, z: z }, t0: Date.now() });
    if (effects.length > 32) { effects.shift(); }
});

// Someone else's drone blew up next to one of ours.
jcmp.events.AddRemoteCallable('fpv/hit', (id, byName) => {
    if (!drone) { return; }
    if (id === droneId) {
        FPV.crash(drone, 'HIT');
        notify('Shot down by ' + byName, 'warn');
        return;
    }
    const w = swarm.wingmen.find(function (x) { return x.id === id; });
    if (w) { FPV.crash(w.s, 'HIT'); }
});

})();
