#!/usr/bin/env node
// Bundles src/client/*.js into packages/fpvdrone/client_package/main.js.
// One file, wrapped in an IIFE, so nothing leaks into the global scope shared
// with other client packages and no reliance on include() semantics.
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'src', 'client');
const OUT = path.join(ROOT, 'packages', 'fpvdrone', 'client_package', 'main.js');
const ORDER = ['math.js', 'physics.js', 'world.js', 'swarm.js', 'remote.js', 'client.js'];

function build() {
    const parts = [
        '// GENERATED by tools/build.js from src/client/ - edit those files, then run `npm run build`.',
        '(function () {',
        'const FPV = {};',
        ''
    ];
    for (const f of ORDER) {
        parts.push('// ===== ' + f + ' =====');
        parts.push(fs.readFileSync(path.join(SRC, f), 'utf8').trimEnd());
        parts.push('');
    }
    parts.push('})();');
    parts.push('');
    const out = parts.join('\n');
    fs.writeFileSync(OUT, out);
    return out;
}

if (require.main === module) {
    const out = build();
    console.log('wrote ' + path.relative(ROOT, OUT) + ' (' + out.length + ' bytes)');
}

module.exports = { build: build, OUT: OUT, ORDER: ORDER };
